"""The LOC cap's scope — what `tools/check_loc.py` does and does not measure.

The cap used to skip every `.md` and `.json` by suffix, which is how the design
record reached 1194 lines unremarked. Now scope is "every text file git knows
about", with an explicit, reasoned exemption list for generated files only.
These tests pin that down so the scope cannot quietly narrow again.
"""

from __future__ import annotations

import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import check_loc

# Files that must be generated by something in tools/ (or by npm) and nothing
# else — the only acceptable reason to be exempt. Keep in step with the
# EXEMPT_PATHS dict; a new entry here means a new generator exists.
DOCUMENTED_GENERATED = {
    "firmware/generated/scenes.yaml",
    "previewer/castle-cue-desk.html",
    "audio/markers.json",
    "web/package-lock.json",
}


class TestScope(unittest.TestCase):
    def setUp(self) -> None:
        self.measured = {rel for _n, rel, _o in check_loc.measure()}

    def test_every_text_kind_is_seen(self) -> None:
        """Markdown, HTML, YAML, CSS and shell are all in scope — no suffix
        earns a pass. Each kind is checked by a file the repo really has."""
        for rel in ("PROJECT_NOTES.md", "docs/WIRING.md",
                    "docs/castle-wiring.html", "firmware/castle.yaml",
                    "previewer/styles.css", "githooks/pre-commit",
                    "Makefile", "tools/check_loc.py", "web/src/main.ts"):
            self.assertIn(rel, self.measured, f"{rel} should be measured")

    def test_scope_is_wide(self) -> None:
        """Suffix spread is the honest signal that nothing is being skipped:
        at least these kinds must appear among the measured files."""
        kinds = {Path(r).suffix for r in self.measured}
        self.assertTrue({".md", ".html", ".yaml", ".css", ".py", ".ts",
                         ".json"} <= kinds, kinds)

    def test_hand_written_json_is_measured(self) -> None:
        """JSON is data, but hand-written JSON is still a file someone edits."""
        self.assertIn("tracks/tracks.json", self.measured)
        self.assertIn("web/package.json", self.measured)

    def test_binary_files_are_skipped(self) -> None:
        """A line count on audio or images means nothing; they are skipped by
        kind, not exempted by name, so the exemption list stays generated-only."""
        for rel in self.measured:
            self.assertNotIn(Path(rel).suffix.lower(), check_loc.BINARY_SUFFIX,
                             f"{rel} is binary and should not be measured")


class TestExemptions(unittest.TestCase):
    def test_exemptions_are_exactly_the_documented_generated_files(self) -> None:
        self.assertEqual(set(check_loc.EXEMPT_PATHS), DOCUMENTED_GENERATED)

    def test_every_exemption_names_its_generator(self) -> None:
        """An exemption without a reason is a loophole. Each must say who
        writes the file — "generated by …" or a lockfile."""
        for rel, why in check_loc.EXEMPT_PATHS.items():
            self.assertTrue("generated by tools/" in why or "lockfile" in why,
                            f"{rel}: reason does not name a generator: {why!r}")

    def test_exempt_files_are_not_measured(self) -> None:
        measured = {rel for _n, rel, _o in check_loc.measure()}
        for rel in check_loc.EXEMPT_PATHS:
            self.assertNotIn(rel, measured)

    def test_exempt_generators_exist(self) -> None:
        """If the generator is gone the file is no longer generated, and the
        exemption is no longer honest."""
        for rel, why in check_loc.EXEMPT_PATHS.items():
            if "generated by tools/" in why:
                gen = why.split("generated by ", 1)[1].split()[0]
                self.assertTrue((ROOT / gen).is_file(), f"{rel}: {gen} missing")


class TestSyntheticTree(unittest.TestCase):
    """Drive `measure()` at a scratch tree to prove the cap bites on prose."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _measure(self, names: list[str]) -> dict[str, tuple[int, bool]]:
        files = [self.tmp / n for n in names]
        rows = check_loc.measure(root=self.tmp, files=files, exempt={})
        return {rel: (n, over) for n, rel, over in rows}

    def test_a_501_line_markdown_fails(self) -> None:
        (self.tmp / "notes.md").write_text("line\n" * 501)
        (self.tmp / "fine.md").write_text("line\n" * 500)
        got = self._measure(["notes.md", "fine.md"])
        self.assertEqual(got["notes.md"], (501, True))
        self.assertEqual(got["fine.md"], (500, False))

    def test_a_501_line_html_and_yaml_fail(self) -> None:
        (self.tmp / "page.html").write_text("<p>x</p>\n" * 501)
        (self.tmp / "cfg.yaml").write_text("- x\n" * 501)
        got = self._measure(["page.html", "cfg.yaml"])
        self.assertTrue(got["page.html"][1])
        self.assertTrue(got["cfg.yaml"][1])

    def test_binary_sniff_skips_nul_bytes(self) -> None:
        (self.tmp / "blob.dat").write_bytes(b"\0\1\2" * 1000)
        (self.tmp / "sound.mp3").write_bytes(b"ID3" + b"x" * 100)
        self.assertEqual(self._measure(["blob.dat", "sound.mp3"]), {})

    def test_exempt_path_is_skipped_even_when_over(self) -> None:
        (self.tmp / "gen.json").write_text("1\n" * 900)
        rows = check_loc.measure(root=self.tmp, files=[self.tmp / "gen.json"],
                                 exempt={"gen.json": "generated by a test"})
        self.assertEqual(rows, [])

    def test_missing_file_is_ignored(self) -> None:
        self.assertEqual(self._measure(["ghost.md"]), {})


if __name__ == "__main__":
    unittest.main()
