"""The LOC cap's scope — what `tools/check_loc.py` does and does not measure.

The cap used to skip every `.md` and `.json` by suffix, which is how the design
record reached 1194 lines unremarked. Now scope is "every text file git knows
about", with three explicit, reasoned exemptions: generated files; the show's
data file, which pays for its exemption with a scene budget instead; and the
grade reports, which are the machine's findings about the repo rather than
part of it. These tests pin that down so the scope cannot quietly narrow
again — and pin the two thresholds (the 500 cap, the hook's 490) with it.
"""

from __future__ import annotations

import contextlib
import io
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import check_loc

# Files that must be generated by something in tools/ (or by npm) and nothing
# else — the only acceptable reason to be exempt. Keep in step with the
# EXEMPT_PATHS dict; a new entry here means a new generator exists.
DOCUMENTED_GENERATED = {
    "firmware/generated/scenes.yaml",
    "audio/markers.json",
    "web/package-lock.json",
    "tests/golden/read_routes.json",
    "tests/golden/scene_errors.json",
}

# The second exemption, and the only kind of file that may take it: data the
# show is written IN, held to a budget of its own rather than to the cap. One
# entry, named here so a second one cannot appear without this line changing.
DOCUMENTED_DATA = {
    "scenes/scenes.yaml",
}

# The third: audit output — findings written ABOUT the repo, by the machine,
# long in proportion to what was found. A pattern rather than a path list
# because every audit writes a new file; pinned here so the pattern cannot
# quietly widen into "anything under .claude/".
DOCUMENTED_AUDIT = {
    ".claude/grade-report*.md",
}


class TestScope(unittest.TestCase):
    def setUp(self) -> None:
        self.measured = {rel for _n, rel, _o in check_loc.measure()}

    def test_every_text_kind_is_seen(self) -> None:
        """Markdown, HTML, YAML, CSS and shell are all in scope — no suffix
        earns a pass. Each kind is checked by a file the repo really has."""
        for rel in (
            "PROJECT_NOTES.md",
            "docs/WIRING.md",
            "docs/castle-wiring.html",
            "firmware/castle.yaml",
            "previewer/styles.css",
            "githooks/pre-commit",
            "Makefile",
            "tools/check_loc.py",
            "web/src/main.ts",
        ):
            self.assertIn(rel, self.measured, f"{rel} should be measured")

    def test_scope_is_wide(self) -> None:
        """Suffix spread is the honest signal that nothing is being skipped:
        at least these kinds must appear among the measured files."""
        kinds = {Path(r).suffix for r in self.measured}
        self.assertLessEqual(
            {".md", ".html", ".yaml", ".css", ".py", ".ts", ".json"}, kinds
        )

    def test_hand_written_json_is_measured(self) -> None:
        """JSON is data, but hand-written JSON is still a file someone edits."""
        self.assertIn("tracks/tracks.json", self.measured)
        self.assertIn("web/package.json", self.measured)

    def test_binary_files_are_skipped(self) -> None:
        """A line count on audio or images means nothing; they are skipped by
        kind, not exempted by name, so the exemption list stays generated-only."""
        for rel in self.measured:
            self.assertNotIn(
                Path(rel).suffix.lower(),
                check_loc.BINARY_SUFFIX,
                f"{rel} is binary and should not be measured",
            )


class TestExemptions(unittest.TestCase):
    def test_exemptions_are_exactly_the_documented_generated_files(self) -> None:
        self.assertEqual(set(check_loc.EXEMPT_PATHS), DOCUMENTED_GENERATED)

    def test_data_exemptions_are_exactly_the_documented_data_files(self) -> None:
        """The data list is the softer of the two — the one a tight deadline
        would be tempted to extend — so it is pinned just as hard."""
        self.assertEqual(set(check_loc.DATA_EXEMPT), DOCUMENTED_DATA)

    def test_the_two_lists_are_the_whole_exemption_and_do_not_overlap(self) -> None:
        """`measure()` skips ALL_EXEMPT, so a path smuggled into neither
        documented set — or quietly added to ALL_EXEMPT directly — fails here.

        The audit exemption is deliberately NOT in ALL_EXEMPT: it is a
        pattern, matched separately by `is_audit_output`, and it is pinned by
        its own tests below."""
        self.assertEqual(
            set(check_loc.ALL_EXEMPT), DOCUMENTED_GENERATED | DOCUMENTED_DATA
        )
        self.assertEqual(
            set(check_loc.EXEMPT_PATHS) & set(check_loc.DATA_EXEMPT), set()
        )

    def test_every_exemption_names_its_generator(self) -> None:
        """An exemption without a reason is a loophole. Each must say who
        writes the file — "generated by …" or a lockfile."""
        for rel, why in check_loc.EXEMPT_PATHS.items():
            self.assertTrue(
                "generated by tools/" in why or "lockfile" in why,
                f"{rel}: reason does not name a generator: {why!r}",
            )

    def test_every_data_exemption_names_the_budget_that_replaces_the_cap(self) -> None:
        """A data file is exempt because a line count is the wrong measure of
        it — not because nobody wants to measure it. The reason must name the
        budget that took the cap's place, and that budget must be enforced."""
        for rel, why in check_loc.DATA_EXEMPT.items():
            self.assertIn("SCENE_LIMIT", why, f"{rel}: no budget named: {why!r}")
        self.assertEqual(check_loc.SCENE_LIMIT, 12)
        self.assertTrue(callable(check_loc.scene_budget))

    def test_audit_exemption_is_exactly_the_documented_pattern(self) -> None:
        self.assertEqual(set(check_loc.AUDIT_EXEMPT), DOCUMENTED_AUDIT)

    def test_the_audit_pattern_covers_the_reports_and_nothing_else(self) -> None:
        """The reason it is a pattern is that each audit writes a new file;
        the reason it is a NARROW pattern is that .claude/ also holds
        hand-written material (the migration plan, launch.json) which stays
        held to the cap like any other file."""
        for rel in (
            ".claude/grade-report.md",
            ".claude/grade-report-2026-08-16.md",
            ".claude/grade-report-2026-08-31-executed.md",
        ):
            self.assertTrue(check_loc.is_audit_output(rel), rel)
        for rel in (
            ".claude/typesafe-migration-plan.md",
            ".claude/launch.json",
            ".claude/grade-report.py",
            "docs/grade-report.md",
            ".claude/notes/grade-report.md",
            "tools/check_loc.py",
        ):
            self.assertFalse(check_loc.is_audit_output(rel), rel)

    def test_every_audit_exemption_says_it_is_not_code(self) -> None:
        """Same rule as the other two lists: the reason carries the weight."""
        for pat, why in check_loc.AUDIT_EXEMPT.items():
            self.assertIn("audit output", why, f"{pat}: {why!r}")

    def test_exempt_files_are_not_measured(self) -> None:
        measured = {rel for _n, rel, _o in check_loc.measure()}
        for rel in check_loc.ALL_EXEMPT:
            self.assertNotIn(rel, measured)
        for rel in measured:
            self.assertFalse(check_loc.is_audit_output(rel), rel)

    def test_exempt_generators_exist(self) -> None:
        """If the generator is gone the file is no longer generated, and the
        exemption is no longer honest."""
        for rel, why in check_loc.EXEMPT_PATHS.items():
            if "generated by tools/" in why:
                gen = why.split("generated by ", 1)[1].split()[0]
                self.assertTrue((ROOT / gen).is_file(), f"{rel}: {gen} missing")


class TestSceneBudget(unittest.TestCase):
    """What scenes.yaml is held to now that it is not held to the cap.

    The board fits ~12 scenes (~9 KB of dram0 each). Dropping the line cap on
    the show file only stays honest if the budget that actually binds it is
    checked in the same place, and fails.
    """

    SHOW = (
        "hardware:\n"
        "  zones:\n"
        "  - {id: towerL, channel: 1}\n"
        "  - {id: door, channel: 3}\n"
        "scenes:\n"
        "  - id: vigil\n"
        "    name: Vigil\n"
        "\n"
        "  - id: storm\n"
        "    name: Storm\n"
    )

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.show = self.tmp / "scenes.yaml"

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_counts_scene_blocks_and_not_the_zone_list(self) -> None:
        """The zone list above `scenes:` uses `- {id: …}` and must not count."""
        self.show.write_text(self.SHOW)
        self.assertEqual(check_loc.count_scenes(self.show), 2)

    def test_a_show_within_the_ceiling_has_no_complaint(self) -> None:
        self.show.write_text(self.SHOW)
        self.assertEqual(check_loc.scene_budget(self.show), (2, None))

    def test_a_thirteenth_scene_fails_and_says_what_to_do_instead(self) -> None:
        blocks = "".join(f"  - id: s{i}\n    name: S{i}\n" for i in range(13))
        self.show.write_text("scenes:\n" + blocks)
        n, complaint = check_loc.scene_budget(self.show)
        self.assertEqual(n, 13)
        assert complaint is not None
        self.assertIn("FAILED", complaint)
        self.assertIn("13", complaint)
        self.assertIn("card-loaded", complaint)

    def test_the_real_show_is_within_its_budget(self) -> None:
        n, complaint = check_loc.scene_budget()
        self.assertIsNone(complaint, complaint)
        self.assertLessEqual(n, check_loc.SCENE_LIMIT)
        self.assertGreater(n, 0, "the show file should hold scenes")

    def test_a_missing_or_shapeless_file_counts_nothing(self) -> None:
        """No scenes: header, no count — the check must not invent a failure
        for a sandboxed or half-written file."""
        self.assertEqual(check_loc.count_scenes(self.tmp / "ghost.yaml"), 0)
        self.show.write_text("hardware: {}\n")
        self.assertEqual(check_loc.count_scenes(self.show), 0)


class TestSyntheticTree(unittest.TestCase):
    """Drive `measure()` at a scratch tree to prove the cap bites on prose."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _measure(self, names: list[str]) -> dict[str, tuple[int, bool]]:
        files = [self.tmp / n for n in names]
        rows = check_loc.measure(root=self.tmp, files=files, exempt={})
        return {rel: (n, over) for n, rel, over in rows}

    def test_a_501_line_markdown_fails(self) -> None:
        (self.tmp / "notes.md").write_text("line\n" * 501)
        (self.tmp / "fine.md").write_text("line\n" * 500)
        got = self._measure(["notes.md", "fine.md"])
        self.assertEqual(got["notes.md"], (501, True))
        self.assertEqual(got["fine.md"], (500, False))

    def test_a_501_line_html_and_yaml_fail(self) -> None:
        (self.tmp / "page.html").write_text("<p>x</p>\n" * 501)
        (self.tmp / "cfg.yaml").write_text("- x\n" * 501)
        got = self._measure(["page.html", "cfg.yaml"])
        self.assertTrue(got["page.html"][1])
        self.assertTrue(got["cfg.yaml"][1])

    def test_binary_sniff_skips_nul_bytes(self) -> None:
        (self.tmp / "blob.dat").write_bytes(b"\0\1\2" * 1000)
        (self.tmp / "sound.mp3").write_bytes(b"ID3" + b"x" * 100)
        self.assertEqual(self._measure(["blob.dat", "sound.mp3"]), {})

    def test_exempt_path_is_skipped_even_when_over(self) -> None:
        (self.tmp / "gen.json").write_text("1\n" * 900)
        rows = check_loc.measure(
            root=self.tmp,
            files=[self.tmp / "gen.json"],
            exempt={"gen.json": "generated by a test"},
        )
        self.assertEqual(rows, [])

    def test_missing_file_is_ignored(self) -> None:
        self.assertEqual(self._measure(["ghost.md"]), {})


class TestThresholds(unittest.TestCase):
    """Two numbers, and the reason there are two (grade report 2026-09-01 I3).

    `make check` and CI enforce the 500-line cap. The pre-commit hook fails
    ten lines earlier, because the hook is the only gate a file passes on its
    way UP: at the cap, a file can legally sit at 499 (castle_fuzz.py did) and
    the next one-line change in unrelated work reddens the commit. The band
    between them is the room that makes a split a decision instead of an
    emergency.
    """

    def test_the_hook_stops_before_the_cap_and_after_the_warning(self) -> None:
        self.assertEqual(check_loc.LIMIT, 500)
        self.assertEqual(check_loc.HOOK_LIMIT, 490)
        self.assertEqual(check_loc.WARN_LIMIT, 450)
        self.assertLess(check_loc.WARN_LIMIT, check_loc.HOOK_LIMIT)
        self.assertLess(check_loc.HOOK_LIMIT, check_loc.LIMIT)

    def test_the_hook_runs_check_loc_in_hook_mode(self) -> None:
        """The threshold only bites if the hook asks for it — this is the
        wiring, and it is one flag away from being silently lost."""
        hook = (ROOT / "githooks" / "pre-commit").read_text()
        self.assertIn("tools/check_loc.py --hook", hook)

    def test_check_mode_passes_a_file_the_hook_would_refuse(self) -> None:
        """495 lines: over the hook's threshold, under the cap. `make check`
        must stay green on it — a tree that already contains such a file (a
        rebase, a merge, a file that predates the threshold) is not broken,
        it just cannot be added to."""
        rows = [(495, "big.py", False)]
        self.assertEqual([r for r in rows if r[0] > check_loc.LIMIT], [])
        self.assertEqual(
            [r for r in rows if r[0] > check_loc.HOOK_LIMIT], [(495, "big.py", False)]
        )

    def test_hook_mode_fails_and_check_mode_does_not_on_the_same_tree(self) -> None:
        """End to end through main(), on a real tree: a 495-line file makes
        `--hook` exit 1 and plain mode exit 0."""
        tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, tmp, True)
        (tmp / "big.py").write_text("x = 1\n" * 495)
        rows = [(495, "big.py", False)]
        with mock.patch.object(check_loc, "measure", return_value=rows):
            out = io.StringIO()
            with contextlib.redirect_stdout(out):
                self.assertEqual(check_loc.main([]), 0)
                self.assertEqual(check_loc.main(["--hook"]), 1)
        text = out.getvalue()
        self.assertIn("LOC check PASS", text)
        self.assertIn("over the 490-line pre-commit threshold", text)
        self.assertIn("The cap itself is 500", text)


if __name__ == "__main__":
    unittest.main()
