#!/usr/bin/env python3
"""Enforce the 500-line file cap — on every text file in the repo.

    tools/check_loc.py            # report, exit 1 if anything is over
    tools/check_loc.py --list     # show the 15 largest files in scope
    tools/check_loc.py --exempt   # show the exemption list with reasons

A cap is only a standard if something checks it, so this runs in `make check`.

Scope is everything git tracks (plus untracked files it would not ignore):
code, config, YAML, CSS, HTML, shell, Makefile, Markdown — prose included. A
1200-line design document is as hard to navigate as a 1200-line module, and
"docs don't count" was how the record quietly reached 1194 lines. Binary files
are skipped because line counts mean nothing for them.

Two kinds of file are exempt, each listed below with its reason:

  - generated and machine-written files. Their size is a property of the
    source they came from; the generator is what should stay small.
  - the show's own data, `scenes/scenes.yaml`. A line count is the wrong
    budget for content — the number that actually constrains the show is how
    many scenes the board can hold — so the file trades the cap for that
    budget, enforced here (SCENE_LIMIT) in the same breath.

Nothing hand-written gets an exemption. Split it instead.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIMIT = 500

# Generated / machine-written files, each with WHY it is exempt. Hand-written
# files never go here — split them instead. Anything not listed is held to
# the cap, whatever its suffix.
EXEMPT_PATHS: dict[str, str] = {
    "firmware/generated/scenes.yaml": "generated by tools/gen_esphome.py from scenes/scenes.yaml",
    "audio/markers.json": "generated by tools/render_audio.py — beat/onset markers for every scene",
    "web/package-lock.json": "npm lockfile, written by npm install",
}

# Data files: content, not code, and held to the budget that actually binds
# them instead of the line cap. Each entry names that budget, and the budget
# is checked here — an exemption whose replacement is only a comment is just
# a hole. Today there is exactly one, and it is the show itself.
DATA_EXEMPT: dict[str, str] = {
    "scenes/scenes.yaml": (
        "show data, budgeted by scene count instead: at most "
        "12 scenes (SCENE_LIMIT, checked below)"
    ),
}

# What measure() actually skips. Two dicts because they are exempt for two
# different reasons and only one of them may ever grow casually.
ALL_EXEMPT: dict[str, str] = {**EXEMPT_PATHS, **DATA_EXEMPT}

# ── The scene budget: what scenes.yaml is held to instead of the cap ──
# Scenes are compile-time objects — each becomes a generated ESPHome script
# costing ~9 KB of the S2's static RAM, which is at ~88% after the tenth.
# Past twelve the answer is the card-loaded cue format, not a thirteenth
# script (scenes/scenes.yaml's own header states the same ceiling).
SCENE_LIMIT = 12
SCENES_FILE = ROOT / "scenes" / "scenes.yaml"

# Binary containers: a line count says nothing about them. Suffix first
# (cheap), then a NUL-byte sniff for anything the suffix list misses.
BINARY_SUFFIX = {
    ".mp3",
    ".wav",
    ".ogg",
    ".flac",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".webp",
    ".svgz",
    ".woff",
    ".woff2",
    ".ttf",
    ".otf",
    ".bin",
    ".elf",
    ".pyc",
    ".zip",
    ".gz",
    ".pdf",
}


def tracked_files() -> list[Path]:
    """Everything git would consider part of the project — including files
    that are not committed yet.

    `git ls-files` alone misses untracked files, which meant the check
    cheerfully reported "largest 440 lines" while a 555-line file sat
    uncommitted in the tree. New code is exactly where the risk is, so a guard
    that only sees committed code catches the problem one commit too late.

    `--others --exclude-standard` adds untracked files while still honouring
    .gitignore, so build output and node_modules stay out of it.
    """
    # check=True: if git fails, fail LOUDLY. Without it a broken git (seen
    # 2026-08-13, a corrupted xattr on the repo root) yields an empty file
    # list and the check "passes" having measured nothing.
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    # --cached and --others can name the same path; dedupe while keeping order.
    seen: set[str] = set()
    files = []
    for line in out.splitlines():
        if line and line not in seen:
            seen.add(line)
            files.append(ROOT / line)
    return files


def is_binary(p: Path) -> bool:
    if p.suffix.lower() in BINARY_SUFFIX:
        return True
    try:
        with p.open("rb") as fh:
            return b"\0" in fh.read(8192)
    except OSError:
        return True


def count_lines(p: Path) -> int:
    with p.open("r", errors="replace") as fh:
        return sum(1 for _ in fh)


def measure(
    root: Path = ROOT,
    files: list[Path] | None = None,
    exempt: dict[str, str] | None = None,
) -> list[tuple[int, str, bool]]:
    """(lines, path, over-cap) for every text file in scope, largest first.

    `root`/`files`/`exempt` exist so tests can point the same logic at a
    synthetic tree; production callers use the defaults.
    """
    exempt = ALL_EXEMPT if exempt is None else exempt
    rows = []
    for p in tracked_files() if files is None else files:
        rel = p.relative_to(root).as_posix()
        if rel in exempt or not p.is_file() or is_binary(p):
            continue
        try:
            n = count_lines(p)
        except OSError:
            continue
        rows.append((n, rel, n > LIMIT))
    return sorted(rows, reverse=True)


def scope_summary(rows: list[tuple[int, str, bool]]) -> str:
    """'60 .ts, 55 .py, …' — so the report shows what the cap actually covers."""
    by_kind: dict[str, int] = {}
    for _n, rel, _o in rows:
        kind = Path(rel).suffix or Path(rel).name
        by_kind[kind] = by_kind.get(kind, 0) + 1
    top = sorted(by_kind.items(), key=lambda kv: (-kv[1], kv[0]))
    return ", ".join(f"{c} {k}" for k, c in top)


def count_scenes(path: Path = SCENES_FILE) -> int:
    """Scene blocks in scenes.yaml — counted by reading, not by parsing.

    This check runs in the pre-commit hook, where the venv may not be on the
    path, so it must not import yaml. The file's shape is fixed and machine-
    read elsewhere by the same convention (`^  - id: ` under a top-level
    `scenes:`; the zone list above it uses the inline `- {id: …}` form).
    """
    try:
        text = path.read_text(errors="replace")
    except OSError:
        return 0
    m = re.search(r"^scenes:[ \t]*$", text, re.MULTILINE)
    if not m:
        return 0
    return len(re.findall(r"^  - id:\s", text[m.end() :], re.MULTILINE))


def scene_budget(path: Path = SCENES_FILE) -> tuple[int, str | None]:
    """(scene count, complaint or None) — the budget scenes.yaml carries in
    place of the line cap."""
    n = count_scenes(path)
    if n <= SCENE_LIMIT:
        return n, None
    return n, (
        f"SCENE budget FAILED — {path.name} holds {n} scenes, "
        f"{n - SCENE_LIMIT} over the {SCENE_LIMIT} this board can hold "
        f"(~9 KB of dram0 each).\n\n"
        "  A thirteenth generated script is not the next step: move the cue "
        "timelines to the card-loaded format (one interpreter, N scenes, flat "
        "RAM) described in scenes/scenes.yaml's header. Raising SCENE_LIMIT "
        "without measuring dram0 on a real compile just moves the crash."
    )


def print_exemptions() -> None:
    print(f"{len(EXEMPT_PATHS)} exempt (generated / machine-written):")
    for rel, why in EXEMPT_PATHS.items():
        print(f"  {rel:<34} {why}")
    print(f"{len(DATA_EXEMPT)} exempt (data, budgeted another way):")
    for rel, why in DATA_EXEMPT.items():
        print(f"  {rel:<34} {why}")


def main() -> int:
    rows = measure()
    if "--list" in sys.argv:
        for n, rel, is_over in rows[:15]:
            print(f"{n:>6}  {'OVER' if is_over else '    '}  {rel}")
        return 0
    if "--exempt" in sys.argv:
        print_exemptions()
        return 0

    over = [(n, rel) for n, rel, o in rows if o]
    n_scenes, scene_complaint = scene_budget()
    if not over and scene_complaint is None:
        biggest = rows[0] if rows else (0, "-", False)
        print(
            f"LOC check PASS — {len(rows)} files in scope, largest "
            f"{biggest[0]} lines ({biggest[1]}), cap {LIMIT}"
        )
        print(f"  scope: {scope_summary(rows)}")
        print(
            f"  exempt: {len(EXEMPT_PATHS)} generated files, "
            f"{len(DATA_EXEMPT)} data file{'' if len(DATA_EXEMPT) == 1 else 's'} "
            f"(--exempt lists them with reasons)"
        )
        print(f"  scenes: {n_scenes} of the {SCENE_LIMIT} this board can hold")
        # The early warning: a file within 50 lines of the cap will cross it
        # mid-feature, forcing a split under pressure instead of on a chosen
        # seam. Naming it now is what makes the cap serve design.
        nearing = [(n, rel) for n, rel, _ in rows if LIMIT - 50 < n <= LIMIT]
        if nearing:
            print(
                f"  nearing the cap ({LIMIT - 50}+): "
                + ", ".join(f"{rel} ({n})" for n, rel in nearing)
            )
        return 0

    if over:
        print(f"LOC check FAILED — {len(over)} file(s) over the {LIMIT}-line cap:\n")
        for n, rel in over:
            print(f"  {n:>6}  {rel}   (+{n - LIMIT})")
        print(
            "\nSplit along a real seam — one module per responsibility, one "
            "document per topic — rather than slicing at the line count. "
            "Only generated files may be exempted (EXEMPT_PATHS, with a reason)."
        )
    if scene_complaint:
        if over:
            print()
        print(scene_complaint)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
