#!/usr/bin/env python3
"""Enforce the 500-line file cap — on every text file in the repo.

    tools/check_loc.py            # report, exit 1 if anything is over
    tools/check_loc.py --list     # show the 15 largest files in scope
    tools/check_loc.py --exempt   # show the exemption list with reasons

A cap is only a standard if something checks it, so this runs in `make check`.

Scope is everything git tracks (plus untracked files it would not ignore):
code, config, YAML, CSS, HTML, shell, Makefile, Markdown — prose included. A
1200-line design document is as hard to navigate as a 1200-line module, and
"docs don't count" was how the record quietly reached 1194 lines. Binary files
are skipped because line counts mean nothing for them.

The only exemptions are generated and machine-written files, listed below with
the reason for each. Their size is a property of the source they came from;
the generator is what should stay small.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIMIT = 500

# Generated / machine-written files, each with WHY it is exempt. Hand-written
# files never go here — split them instead. Anything not listed is held to
# the cap, whatever its suffix.
EXEMPT_PATHS: dict[str, str] = {
    "firmware/generated/scenes.yaml": "generated by tools/gen_esphome.py from scenes/scenes.yaml",
    # Belt and braces: the page is gitignored (.gitignore:40), so
    # `git ls-files --exclude-standard` never hands it to the check and this
    # line does nothing today. It stays as the standing answer for the day
    # someone un-ignores the blob again.
    "previewer/castle-cue-desk.html": "generated by tools/gen_previewer.py (the whole cue desk, audio inlined)",
    "audio/markers.json": "generated by tools/render_audio.py — beat/onset markers for every scene",
    "web/package-lock.json": "npm lockfile, written by npm install",
}

# Binary containers: a line count says nothing about them. Suffix first
# (cheap), then a NUL-byte sniff for anything the suffix list misses.
BINARY_SUFFIX = {
    ".mp3",
    ".wav",
    ".ogg",
    ".flac",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".webp",
    ".svgz",
    ".woff",
    ".woff2",
    ".ttf",
    ".otf",
    ".bin",
    ".elf",
    ".pyc",
    ".zip",
    ".gz",
    ".pdf",
}


def tracked_files() -> list[Path]:
    """Everything git would consider part of the project — including files
    that are not committed yet.

    `git ls-files` alone misses untracked files, which meant the check
    cheerfully reported "largest 440 lines" while a 555-line file sat
    uncommitted in the tree. New code is exactly where the risk is, so a guard
    that only sees committed code catches the problem one commit too late.

    `--others --exclude-standard` adds untracked files while still honouring
    .gitignore, so build output and node_modules stay out of it.
    """
    # check=True: if git fails, fail LOUDLY. Without it a broken git (seen
    # 2026-08-13, a corrupted xattr on the repo root) yields an empty file
    # list and the check "passes" having measured nothing.
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    # --cached and --others can name the same path; dedupe while keeping order.
    seen: set[str] = set()
    files = []
    for line in out.splitlines():
        if line and line not in seen:
            seen.add(line)
            files.append(ROOT / line)
    return files


def is_binary(p: Path) -> bool:
    if p.suffix.lower() in BINARY_SUFFIX:
        return True
    try:
        with p.open("rb") as fh:
            return b"\0" in fh.read(8192)
    except OSError:
        return True


def count_lines(p: Path) -> int:
    with p.open("r", errors="replace") as fh:
        return sum(1 for _ in fh)


def measure(
    root: Path = ROOT,
    files: list[Path] | None = None,
    exempt: dict[str, str] | None = None,
) -> list[tuple[int, str, bool]]:
    """(lines, path, over-cap) for every text file in scope, largest first.

    `root`/`files`/`exempt` exist so tests can point the same logic at a
    synthetic tree; production callers use the defaults.
    """
    exempt = EXEMPT_PATHS if exempt is None else exempt
    rows = []
    for p in tracked_files() if files is None else files:
        rel = p.relative_to(root).as_posix()
        if rel in exempt or not p.is_file() or is_binary(p):
            continue
        try:
            n = count_lines(p)
        except OSError:
            continue
        rows.append((n, rel, n > LIMIT))
    return sorted(rows, reverse=True)


def scope_summary(rows: list[tuple[int, str, bool]]) -> str:
    """'60 .ts, 55 .py, …' — so the report shows what the cap actually covers."""
    by_kind: dict[str, int] = {}
    for _n, rel, _o in rows:
        kind = Path(rel).suffix or Path(rel).name
        by_kind[kind] = by_kind.get(kind, 0) + 1
    top = sorted(by_kind.items(), key=lambda kv: (-kv[1], kv[0]))
    return ", ".join(f"{c} {k}" for k, c in top)


def print_exemptions() -> None:
    print(f"{len(EXEMPT_PATHS)} exempt (generated / machine-written):")
    for rel, why in EXEMPT_PATHS.items():
        print(f"  {rel:<34} {why}")


def main() -> int:
    rows = measure()
    if "--list" in sys.argv:
        for n, rel, is_over in rows[:15]:
            print(f"{n:>6}  {'OVER' if is_over else '    '}  {rel}")
        return 0
    if "--exempt" in sys.argv:
        print_exemptions()
        return 0

    over = [(n, rel) for n, rel, o in rows if o]
    if not over:
        biggest = rows[0] if rows else (0, "-", False)
        print(
            f"LOC check PASS — {len(rows)} files in scope, largest "
            f"{biggest[0]} lines ({biggest[1]}), cap {LIMIT}"
        )
        print(f"  scope: {scope_summary(rows)}")
        print(
            f"  exempt: {len(EXEMPT_PATHS)} generated files "
            f"(--exempt lists them with reasons)"
        )
        # The early warning: a file within 50 lines of the cap will cross it
        # mid-feature, forcing a split under pressure instead of on a chosen
        # seam. Naming it now is what makes the cap serve design.
        nearing = [(n, rel) for n, rel, _ in rows if LIMIT - 50 < n <= LIMIT]
        if nearing:
            print(
                f"  nearing the cap ({LIMIT - 50}+): "
                + ", ".join(f"{rel} ({n})" for n, rel in nearing)
            )
        return 0

    print(f"LOC check FAILED — {len(over)} file(s) over the {LIMIT}-line cap:\n")
    for n, rel in over:
        print(f"  {n:>6}  {rel}   (+{n - LIMIT})")
    print(
        "\nSplit along a real seam — one module per responsibility, one "
        "document per topic — rather than slicing at the line count. "
        "Only generated files may be exempted (EXEMPT_PATHS, with a reason)."
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
