#!/usr/bin/env python3
"""Enforce the 500-line file cap.

    tools/check_loc.py            # report, exit 1 if anything is over
    tools/check_loc.py --list     # show the 15 largest tracked files

A cap is only a standard if something checks it, so this runs in `make check`.

Generated files are exempt — their size is a property of the source they came
from, and the generator is what should stay small. Prose is exempt too: a long
design document is not the same problem as a long module.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIMIT = 500

# Exempt, with reasons. Anything not listed here is held to the cap.
EXEMPT_SUFFIX = {".md", ".json", ".mp3", ".wav", ".csv", ".lock"}
EXEMPT_PATHS = {
    "firmware/generated/scenes.yaml",   # generated by tools/gen_esphome.py
    "previewer/castle-cue-desk.html",   # generated by tools/gen_previewer.py
}


def tracked_files() -> list[Path]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT,
                         capture_output=True, text=True).stdout
    return [ROOT / line for line in out.splitlines() if line]


def measure() -> list[tuple[int, str, bool]]:
    rows = []
    for p in tracked_files():
        rel = str(p.relative_to(ROOT))
        if p.suffix in EXEMPT_SUFFIX or rel in EXEMPT_PATHS or not p.exists():
            continue
        try:
            n = sum(1 for _ in p.open("r", errors="replace"))
        except OSError:
            continue
        rows.append((n, rel, n > LIMIT))
    return sorted(rows, reverse=True)


def main() -> int:
    rows = measure()
    if "--list" in sys.argv:
        for n, rel, over in rows[:15]:
            print(f"{n:>6}  {'OVER' if over else '    '}  {rel}")
        return 0

    over = [(n, rel) for n, rel, o in rows if o]
    if not over:
        biggest = rows[0] if rows else (0, "-", False)
        print(f"LOC check passed — {len(rows)} files, largest "
              f"{biggest[0]} lines ({biggest[1]}), cap {LIMIT}")
        return 0

    print(f"LOC check FAILED — {len(over)} file(s) over the {LIMIT}-line cap:\n")
    for n, rel in over:
        print(f"  {n:>6}  {rel}   (+{n - LIMIT})")
    print("\nSplit along a real seam — one module per responsibility — rather "
          "than slicing at the line count.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
