"""The audio half of the firmware generator, split from gen_esphome.py.

One emitter, fed by the scenes.yaml doc: the SD `sfx` — stream each scene's
track off the card over loopback — plus its boot manifest check. Split at the
500-line cap on the honest seam: nothing here knows about cues or rigs, only
which bytes play and from where.

It emitted three until 2026-09-01. The other two — a `media_player` manifest
naming one embedded `snd_<id>` per scene, and a FLASH `sfx` that played it —
belonged to the all-in-flash build, which was retired when the show's songs
grew past what an OTA slot can hold. See docs/notes/03-build.md §12.15.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from gen_show import emit_manifest_check

HEADER = """# GENERATED BY tools/gen_esphome.py — DO NOT EDIT
#
# Source of truth: scenes/scenes.yaml
# Regenerate with:  make generate
#
# Each scene is a script: start its audio file, then step the light cues.
# Timings are deltas between absolute cue times from the source file.
"""

LAMBDA = "      - lambda: |-"
MODE_RESTART = "    mode: restart"
THEN = "    then:"


def emit_audio_sd(doc: Mapping[str, Any]) -> str:
    """SD sfx: STREAM the scene's track off the card through the device's own
    web server over loopback — a real streaming source with zero new
    decoder code, no PSRAM cap, no whole-file loads. A missing card plays
    the embedded chirp, which is the only audio left in the image."""
    sd = [
        HEADER,
        "",
        "script:",
        "  - id: sfx",
        MODE_RESTART,
        "    parameters:",
        "      track: string",
        THEN,
        "      - text_sensor.template.publish:",
        "          id: current_track",
        "          state: !lambda 'return track;'",
        LAMBDA,
        "          if (!castle_sd::g_mounted) {",
        '            ESP_LOGW("castle", "no SD card — playing the fallback chirp");',
        "            id(castle_media)->play_file(id(snd_chirp), true, false);",
        "            return;",
        "          }",
        "          auto call = id(castle_media)->make_call();",
        '          call.set_media_url("http://127.0.0.1:8080/sd/scenes/" + track + ".mp3");',
        "          call.set_announcement(true);",
        "          call.perform();",
        "",
    ]
    sd += emit_manifest_check(doc)
    return "\n".join(sd)
