#!/usr/bin/env python3
"""Bake the web remote's URL into a QR bitmap the eInk screen can blit.

The castle's screen shows a QR code so a phone can reach the web remote
without typing an IP in the dark. Generating the code ON the device would
mean vendoring a C QR encoder (~500 lines) for a value that changes roughly
never — the router reserves 10.27.27.7 for the castle. So the code is baked
at build time instead, and the day the address changes:

    tools/gen_qr.py http://<new-ip>/

writes a fresh firmware/generated/qr_castle.h and the next OTA carries it.
"""

from __future__ import annotations

import sys
from pathlib import Path

import segno

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware" / "generated" / "qr_castle.h"
DEFAULT_URL = "http://10.27.27.7/remote"


def main() -> int:
    url = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_URL
    qr = segno.make(url, error="m")
    matrix = [list(row) for row in qr.matrix]
    n = len(matrix)
    row_bytes = (n + 7) // 8

    rows = []
    for row in matrix:
        packed = bytearray(row_bytes)
        for x, bit in enumerate(row):
            if bit:
                packed[x // 8] |= 0x80 >> (x % 8)
        rows.append(", ".join(f"0x{b:02x}" for b in packed))

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "#pragma once\n"
        f"// Generated by tools/gen_qr.py — do not edit.\n"
        f"// Encodes: {url}\n"
        "#include <cstdint>\n\n"
        "namespace castle_qr {\n"
        f"inline constexpr const char *URL = \"{url}\";\n"
        f"inline constexpr int SIZE = {n};        // modules per side\n"
        f"inline constexpr int ROW_BYTES = {row_bytes};\n"
        "inline constexpr uint8_t BITS[] = {   // MSB-first per row\n"
        + "".join(f"    {r},\n" for r in rows)
        + "};\n"
        "}  // namespace castle_qr\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {n}x{n} modules for {url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
