#!/usr/bin/env python3
"""Generate the ESPHome scene scripts from scenes.yaml.

Hand-writing these would mean the cue timings in the previewer and the cue
timings on the device drift apart within a week. They come from one file
instead.

    tools/gen_esphome.py        # writes firmware/generated/scenes.yaml

Each scene becomes an ESPHome `script` that plays its audio file and then walks
the light cues as a series of delays. Cues are emitted as *deltas* between
absolute timestamps, because ESPHome scripts step forward with `delay:`.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml
from gen_rig import emit_lights, emit_rig_header
from gen_show import emit_manifest_check, emit_show_playlist

# The pulse expansion (what a `pulse:` stream MEANS) lives in
# pulse_expand.py; this file only decides how the device is told.
# round3/section_gates stay re-exported because gen_previewer and the
# parity tests read the whole contract through this module.
from pulse_dynamics import round3, section_gates  # noqa: F401 (re-export)
from pulse_expand import DEFAULT_DECAY, WHITE, pulse_cues
from rig_layout import zone_layouts

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scenes" / "scenes.yaml"
MARKERS = ROOT / "audio" / "markers.json"
OUT = ROOT / "firmware" / "generated" / "scenes.yaml"
RIG_OUT = ROOT / "firmware" / "generated" / "rig.h"
LIGHTS_OUT = ROOT / "firmware" / "generated" / "lights.yaml"
MEDIA_OUT = ROOT / "firmware" / "generated" / "media_files.yaml"
AUDIO_FLASH = ROOT / "firmware" / "generated" / "audio_flash.yaml"
AUDIO_SD = ROOT / "firmware" / "generated" / "audio_sd.yaml"

HEADER = """# GENERATED BY tools/gen_esphome.py — DO NOT EDIT
#
# Source of truth: scenes/scenes.yaml
# Regenerate with:  make generate
#
# Each scene is a script: start its audio file, then step the light cues.
# Timings are deltas between absolute cue times from the source file.
"""

# Contract with the Effect enum in firmware/castle_effects.h. Integers rather
# than strings so the render hot path is a switch, not a string compare.
EFFECT_IDS = {
    "off": 0, "candle": 1, "ember": 2, "furnace": 3, "spirit": 4, "eyes": 5,
    "seance": 6, "wisp": 7, "mansion": 8, "chill": 9, "throb": 10, "strobe": 11,
    "blood": 12,
}

# Per-pixel texture vocabularies — indices match castle_effects.h AND
# web/src/effects.ts. Three files, one contract.
OVERLAY_IDS = {"none": 0, "sparkle": 1, "chase": 2, "meteor": 3}
PALETTE_IDS = {"haunt": 0, "ember": 1, "moonlight": 2, "toxic": 3}
FLASH_MODE_IDS = {"all": 0, "scatter": 1, "center": 2, "ring": 3}


def zone_pixels(layouts: dict, zones: list[dict]) -> dict[str, tuple[int, int]]:
    """Map each zone to its [first, last] index if they shared ONE chain.

    Only meaningful for a rig whose zones are all the same colour type; the
    device now drives a strip per zone (see `emit_lights`). Kept because the
    ranges are still the thing you want when tracing a dark window on a
    single-chain build. Counts come from the layouts, not `z["pixels"]` —
    a zone that names a fixed-count fixture (ring12, jewel7) carries no
    `pixels:` key at all, and reading the raw dict here is how the door's
    range once printed 7 px worth while the strip drove 12.
    """
    out = {}
    at = 0
    for z in zones:
        n = layouts[z["id"]].n
        out[z["id"]] = (at, at + max(0, n - 1))
        at += n
    return out


def eff_id(name: str, scene_id: str) -> int:
    if name not in EFFECT_IDS:
        raise SystemExit(f"scene {scene_id}: unknown effect {name!r}")
    return EFFECT_IDS[name]




def emit_scene(scene: dict, zones: list[dict], idx: int, markers: dict) -> list[str]:
    zone_ids = [z["id"] for z in zones]
    sid = scene["id"]
    lines: list[str] = []
    a = lines.append

    a(f"  # ── {scene['name']} ({scene['kind']}) " + "─" * max(0, 42 - len(scene["name"])))
    a(f"  - id: scene_{sid}")
    a("    mode: restart")
    a("    then:")
    a(f"      - logger.log: 'scene {sid}'")
    # Everyone downstream — the web page's chip, Home Assistant, the tools —
    # learns what is running from this one sensor.
    a("      - text_sensor.template.publish:")
    a("          id: current_scene")
    a(f"          state: '{sid}'")

    # Reset to the scene's base state, so a scene always starts known-good
    # even if it interrupted another mid-cue — including flash colour and
    # decay, which the previous scene's strikes may have recoloured.
    levels = scene.get("levels") or {}
    zdetail = scene.get("zones") or {}

    def zone_sets(i: int, z: str) -> str:
        d = zdetail.get(z) or {}
        center = eff_id(d["center"], sid) if d.get("center") else -1
        ov = OVERLAY_IDS.get(d.get("overlay", "none"), 0)
        pal = PALETTE_IDS.get(d.get("palette", "haunt"), 0)
        phase = float(d.get("phase", 0.0))
        return (
            f"id(zone_effect)[{i}] = {eff_id(scene['base'].get(z, 'off'), sid)};"
            f" id(zone_flash)[{i}] = 0.0f;"
            f" id(zone_flash_target)[{i}] = 0.0f;"
            f" id(zone_flash_decay)[{i}] = {DEFAULT_DECAY}f;"
            f" id(zone_level)[{i}] = {float(levels.get(z, 1.0)):.2f}f;"
            f" id(zone_center)[{i}] = {center};"
            f" id(zone_overlay)[{i}] = {ov};"
            f" id(zone_palette)[{i}] = {pal};"
            f" id(zone_phase)[{i}] = {phase:.2f}f;"
            f" id(zone_flash_mode)[{i}] = 0;"
            + "".join(f" id(zone_flash_col)[{i * 4 + k}] = 1.0f;" for k in range(4))
        )

    sets = " ".join(zone_sets(i, z) for i, z in enumerate(zone_ids))
    a(f"      - lambda: '{sets}'")
    a(f"      - media_player.volume_set: {scene.get('volume', 0.8)}")
    # Audio goes through the generated `sfx` dispatch script rather than a
    # direct play action, because the two builds implement it differently:
    # the flash build plays the embedded file, the SD build streams the same
    # track off the card (see audio_flash.yaml / audio_sd.yaml below).
    a("      - script.execute:")
    a("          id: sfx")
    a(f"          track: '{idx:02d}_{sid}'")

    prev = 0
    all_cues = (scene.get("cues") or []) + pulse_cues(scene, markers)
    for cue in sorted(all_cues, key=lambda c: c["t"]):
        dt = cue["t"] - prev
        if dt > 0:
            a(f"      - delay: {dt}ms")
            prev = cue["t"]
        note = f"    # {cue['note']}" if cue.get("note") else ""
        if cue["op"] == "set":
            i = zone_ids.index(cue["zone"])
            stmt = f"id(zone_effect)[{i}] = {eff_id(cue['effect'], sid)};"
            if "level" in cue:
                stmt += f" id(zone_level)[{i}] = {float(cue['level']):.2f}f;"
            a(f"      - lambda: '{stmt}'{note}")
        elif cue["op"] == "strike":
            targets = (cue.get("targets")
                       or ([cue["zone"]] if cue.get("zone") else None)
                       or zone_ids)
            # `ms` documents the intended visual length; the actual fall is
            # the per-zone decay factor, applied every frame in the render
            # loop. Colour is per strike: lightning white, heartbeat red.
            amt = float(cue.get("intensity", 1.0))
            col = cue.get("color", WHITE)
            dec = float(cue.get("decay", DEFAULT_DECAY))
            mode = FLASH_MODE_IDS.get(cue.get("pixels", "all"), 0)
            attack = int(cue.get("attack", 0))
            parts = []
            for z in targets:
                i = zone_ids.index(z)
                if attack > 0:
                    # #10: swell to the peak over `attack` ms — the render
                    # loop climbs by _rise per 16 ms frame, then decays.
                    parts.append(f"id(zone_flash_target)[{i}] = {amt:.3f}f;")
                    parts.append(
                        f"id(zone_flash_rise)[{i}] = {amt * 16.0 / attack:.4f}f;")
                else:
                    parts.append(f"id(zone_flash)[{i}] = {amt:.3f}f;")
                    parts.append(f"id(zone_flash_target)[{i}] = 0.0f;")
                parts.append(f"id(zone_flash_decay)[{i}] = {dec}f;")
                # Mask + epoch: WHERE on the jewel this strike lands, and a
                # fresh scatter subset each time (mirrors fireCues in show.ts).
                parts.append(f"id(zone_flash_mode)[{i}] = {mode};")
                parts.append(f"id(zone_flash_epoch)[{i}] = (id(zone_flash_epoch)[{i}] + 1) % 1000;")
                parts += [f"id(zone_flash_col)[{i * 4 + k}] = {float(col[k]):.2f}f;"
                          for k in range(4)]
            a(f"      - lambda: '{' '.join(parts)}'{note}")
        else:
            raise SystemExit(f"scene {sid}: unknown cue op {cue['op']!r}")

    tail = scene["duration_ms"] - prev
    if tail > 0:
        a(f"      - delay: {tail}ms")
    if scene.get("loop"):
        a(f"      - script.execute: scene_{sid}")
    a("")
    return lines



def main() -> int:
    doc = yaml.safe_load(SRC.read_text())
    zones = doc["zones"]
    per = doc["hardware"]["pixels_per_zone"]
    # A zone may now name its own fixture; `pixels_per_zone` is the fallback
    # for one that does not, which is what keeps an unedited scenes.yaml
    # building. See tools/rig_layout.py.
    layouts = zone_layouts(zones, per)
    total = sum(layouts[z["id"]].n for z in zones)

    out = [HEADER, ""]
    out.append(f"# {len(zones)} zones, {total} pixels — one strip each")
    for zid, (lo, hi) in zone_pixels(layouts, zones).items():
        out.append(f"#   {zid:<8} {layouts[zid].n:>2} px "
                   f"(chain equivalent {lo}-{hi})")
    out.append("")
    out.append("script:")

    markers = json.loads(MARKERS.read_text()) if MARKERS.exists() else {}
    if not markers:
        print("note: no audio/markers.json — run `make audio` first; no beat pulses")
    for i, scene in enumerate(doc["scenes"], start=1):
        out.extend(emit_scene(scene, zones, i, markers))

    # A single stop script, so "blackout" is one call from anywhere.
    #
    # It clears the whole per-zone texture, not just the base effect. The
    # render loop draws the centre pixel from zone_center whenever that is
    # set, and composites the overlay on top of whatever the base is — so a
    # stop that only zeroed zone_effect left vigil's centre embers burning
    # and the door still sparkling, on a castle that was supposed to be dark
    # (tests/cxx/render_check.cpp shows sparkle/meteor/chase all ADD light
    # to a black base). A pending strike swell is cancelled for the same
    # reason: it would otherwise climb, then fall, after the stop.
    out.append("  # ── Blackout ─────────────────────────────────────")
    out.append("  - id: scene_stop")
    out.append("    mode: restart")
    out.append("    then:")
    stop = " ".join(
        f"id(zone_effect)[{i}] = 0; id(zone_center)[{i}] = -1;"
        f" id(zone_overlay)[{i}] = 0; id(zone_flash)[{i}] = 0.0f;"
        f" id(zone_flash_target)[{i}] = 0.0f;" for i in range(len(zones))
    )
    out.append(f"      - lambda: '{stop}'")
    out.append("      - media_player.stop:")
    out.append("      - text_sensor.template.publish:")
    out.append("          id: current_scene")
    out.append("          state: 'stop'")
    out.append("      - text_sensor.template.publish:")
    out.append("          id: current_track")
    out.append("          state: ''")
    out.append("")

    # Scene dispatch by NAME, for every caller that only has a string: the
    # web server's /api/scene, the PIR's configurable scene select, tools.
    # Generated so a new scene is automatically reachable everywhere.
    out.append("  # ── Dispatch by name ─────────────────────────────")
    out.append("  - id: run_scene")
    out.append("    mode: restart")
    out.append("    parameters:")
    out.append("      scene: string")
    out.append("    then:")
    out.append("      - lambda: |-")
    out.append("          // Stop every scene script first. Without this a looping")
    out.append("          // scene's pending delay re-fires AFTER the new scene starts")
    out.append("          // and takes the stage back — two loops fighting forever.")
    out.extend(f"          id(scene_{scene['id']})->stop();"
               for scene in doc["scenes"])
    for j, scene in enumerate(doc["scenes"]):
        kw = "if" if j == 0 else "else if"
        out.append(f"          {kw} (scene == \"{scene['id']}\") "
                   f"id(scene_{scene['id']})->execute();")
    out.append("          else if (scene == \"stop\") id(scene_stop)->execute();")
    out.append("          else ESP_LOGW(\"castle\", \"unknown scene '%s'\", scene.c_str());")
    out.append("")
    out.extend(emit_show_playlist(doc))

    # Show-state sensors and the PIR's configuration entities. Generated here
    # because the scene list is: the PIR select's options ARE the scenes.
    scene_ids = [s["id"] for s in doc["scenes"]]
    pir_default = "approach" if "approach" in scene_ids else scene_ids[0]
    out += [
        "text_sensor:",
        "  - platform: template",
        "    id: current_scene",
        "    name: 'Current scene'",
        "  - platform: template",
        "    id: current_track",
        "    name: 'Current track'",
        "",
        "# Motion is configuration, not code: which scene fires, how long the",
        "# lockout is, and whether the sensor is armed at all — all changeable",
        "# from the web panel or Home Assistant, all persisted.",
        "select:",
        "  - platform: template",
        "    name: 'PIR scene'",
        "    id: pir_scene",
        "    optimistic: true",
        "    restore_value: true",
        f"    options: [{', '.join(scene_ids)}, stop]",
        f"    initial_option: {pir_default}",
        "number:",
        "  - platform: template",
        "    name: 'PIR cooldown'",
        "    id: pir_cooldown",
        "    optimistic: true",
        "    restore_value: true",
        "    min_value: 5",
        "    max_value: 600",
        "    step: 5",
        "    initial_value: 60",
        "    unit_of_measurement: s",
        "switch:",
        "  - platform: template",
        "    name: 'PIR armed'",
        "    id: pir_armed",
        "    optimistic: true",
        "    restore_mode: RESTORE_DEFAULT_ON",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))

    # The media files each scene plays.
    #
    # These used to be hand-maintained in castle.yaml, listing the eight scenes
    # that existed when it was written — while this generator happily emitted
    # `media_file: snd_<id>` for every scene in scenes.yaml. So a scene added
    # any other way, including through the cue desk's own "Make scene" button,
    # produced a config that referenced an id nothing declared:
    #
    #     Couldn't find ID 'snd_the_ballad_of_the_witches__road_'
    #
    # The previewer rebuilt fine, which is what made it convincing; only the
    # firmware build failed, and only when someone next tried to flash. Both
    # halves come from scenes.yaml now, so they cannot disagree.
    files = [HEADER, "",
             "# One entry per scene, matching the `snd_<id>` ids the scripts",
             "# above reference. Generated: do not hand-edit.", ""]
    for i, scene in enumerate(doc["scenes"], start=1):
        files.append(f"- id: snd_{scene['id']}")
        files.append(f"  file: ../audio/{i:02d}_{scene['id']}.mp3")
    MEDIA_OUT.write_text("\n".join(files) + "\n")

    # The two implementations of `sfx` — the audio half of every scene.
    #
    # FLASH (castle.yaml): play the file embedded in the image. Costs ~600 KB
    # of a 1.75 MB OTA slot, works with nothing attached.
    #
    # SD (castle_sd.yaml, via !extend): STREAM the same track off the card
    # through the device's own web server over loopback. The media pipeline
    # already knows how to read a URL; pointing it at 127.0.0.1 turns the SD
    # card into a real streaming source with zero new decoder code — no PSRAM
    # cap, no whole-file loads. If the card is missing, the embedded chirp
    # (the only file the SD build keeps in flash) says so audibly.
    flash = [HEADER, "", "script:",
             "  - id: sfx",
             "    mode: restart",
             "    parameters:",
             "      track: string",
             "    then:",
             "      - text_sensor.template.publish:",
             "          id: current_track",
             "          state: !lambda 'return track;'",
             "      - lambda: |-",
             "          esphome::audio::AudioFile *f = nullptr;"]
    for i, scene in enumerate(doc["scenes"], start=1):
        kw = "if" if i == 1 else "else if"
        flash.append(f"          {kw} (track == \"{i:02d}_{scene['id']}\") "
                     f"f = id(snd_{scene['id']});")
    flash += ["          if (f != nullptr) id(castle_media)->play_file(f, true, false);",
              ("          else ESP_LOGW(\"castle\", \"no embedded audio for '%s'\","
               " track.c_str());"), ""]
    AUDIO_FLASH.write_text("\n".join(flash))

    sd = [HEADER, "", "script:",
          "  - id: sfx",
          "    mode: restart",
          "    parameters:",
          "      track: string",
          "    then:",
          "      - text_sensor.template.publish:",
          "          id: current_track",
          "          state: !lambda 'return track;'",
          "      - lambda: |-",
          "          if (!castle_sd::g_mounted) {",
          "            ESP_LOGW(\"castle\", \"no SD card — playing the fallback chirp\");",
          "            id(castle_media)->play_file(id(snd_chirp), true, false);",
          "            return;",
          "          }",
          "          auto call = id(castle_media)->make_call();",
          "          call.set_media_url(\"http://127.0.0.1:8080/sd/scenes/\" + track + \".mp3\");",
          "          call.set_announcement(true);",
          "          call.perform();", ""]
    sd += emit_manifest_check(doc)
    AUDIO_SD.write_text("\n".join(sd))

    n_cues = sum(len(s.get("cues") or []) for s in doc["scenes"])
    # Geometry the firmware indexes, and the strips that use it. Written
    # from the same `layouts` the cue scripts above were emitted against, so
    # a zone can never end up with cues aimed at pixels its strip lacks.
    RIG_OUT.write_text(emit_rig_header(layouts, zones))
    LIGHTS_OUT.write_text(emit_lights(layouts, zones, per))

    print(f"wrote {OUT.relative_to(ROOT)} + {MEDIA_OUT.name} "
          f"+ {RIG_OUT.name} + {LIGHTS_OUT.name}")
    print(f"  {len(doc['scenes'])} scenes, {n_cues} cues, {total} pixels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
