#!/usr/bin/env python3
"""Generate the ESPHome scene scripts from scenes.yaml.

Hand-writing these would mean the cue timings in the previewer and the cue
timings on the device drift apart within a week. They come from one file
instead.

    tools/gen_esphome.py        # writes firmware/generated/scenes.yaml

Each scene becomes an ESPHome `script` that plays its audio file and then walks
the light cues as a series of delays. Cues are emitted as *deltas* between
absolute timestamps, because ESPHome scripts step forward with `delay:`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import build_paths as bp
import gen_esphome_audio as ga
import yaml
from effect_vocab import EFFECT_IDS, FLASH_MODE_IDS, OVERLAY_IDS, PALETTE_IDS
from gen_rig import emit_lights, emit_rig_header
from gen_show import emit_show_playlist

# The pulse expansion (what a `pulse:` stream MEANS) lives in
# pulse_expand.py; this file only decides how the device is told.
# round3/section_gates stay re-exported because gen_previewer and the
# parity tests read the whole contract through this module.
from pulse_dynamics import round3, section_gates, thin_pulses
from pulse_expand import DEFAULT_DECAY, WHITE, pulse_cues
from rig_layout import Layout, zone_layouts
from scene_schema import validate as validate_scene

ROOT = Path(__file__).resolve().parent.parent
# Source and outputs both follow build_paths.py: a sandboxed studio (its own
# CASTLE_SCENES) generates under its own build root, never the repo's.
SRC = bp.SCENES
MARKERS = bp.AUDIO / "markers.json"
OUT = bp.GENERATED / "scenes.yaml"
RIG_OUT = bp.GENERATED / "rig.h"
LIGHTS_OUT = bp.GENERATED / "lights.yaml"
MEDIA_OUT = bp.GENERATED / "media_files.yaml"
AUDIO_FLASH = bp.GENERATED / "audio_flash.yaml"
AUDIO_SD = bp.GENERATED / "audio_sd.yaml"

HEADER = """# GENERATED BY tools/gen_esphome.py — DO NOT EDIT
#
# Source of truth: scenes/scenes.yaml
# Regenerate with:  make generate
#
# Each scene is a script: start its audio file, then step the light cues.
# Timings are deltas between absolute cue times from the source file.
"""

# The effect/overlay/palette/flash-mask names and their firmware ids live in
# tools/effect_vocab.py — one table for both generators, the schema and the
# parity test. Re-exported here so `ge.EFFECT_IDS` keeps working.
# (plus the pulse contract: gen_previewer, fuzz_check and the parity tests
# read DEFAULT_DECAY/WHITE/pulse_cues/round3/section_gates/thin_pulses
# through this module — see the import comment above.)
__all__ = [
    "DEFAULT_DECAY",
    "EFFECT_IDS",
    "FLASH_MODE_IDS",
    "OVERLAY_IDS",
    "PALETTE_IDS",
    "WHITE",
    "pulse_cues",
    "round3",
    "section_gates",
    "thin_pulses",
]


def zone_pixels(
    layouts: dict[str, Layout], zones: list[dict[str, Any]]
) -> dict[str, tuple[int, int]]:
    """Map each zone to its [first, last] index if they shared ONE chain.

    Only meaningful for a rig whose zones are all the same colour type; the
    device now drives a strip per zone (see `emit_lights`). Kept because the
    ranges are still the thing you want when tracing a dark window on a
    single-chain build. Counts come from the layouts, not `z["pixels"]` —
    a zone that names a fixed-count fixture (ring12, jewel7) carries no
    `pixels:` key at all, and reading the raw dict here is how the door's
    range once printed 7 px worth while the strip drove 12.
    """
    out = {}
    at = 0
    for z in zones:
        n = layouts[z["id"]].n
        out[z["id"]] = (at, at + max(0, n - 1))
        at += n
    return out


def eff_id(name: str, scene_id: str) -> int:
    if name not in EFFECT_IDS:
        raise SystemExit(f"scene {scene_id}: unknown effect {name!r}")
    return EFFECT_IDS[name]


# ESPHome stops and polls a script by walking its action chain RECURSIVELY
# (Action::stop_complex -> next_->stop_complex -> ...), one stack frame per
# action, on the 8 KB loop task. run_scene stops every scene script before it
# starts the next, so a 457-action scene took the castle down on every scene
# switch (v5.27, 2026-08-21 — PANIC, then the rollback counter). No script may
# be long: a scene is a head script plus `cont_<id>_N` continuations of at
# most CHUNK actions, each chained to the next by its final action. The
# delays inside a continuation are untouched, so the timeline is identical.
CHUNK = 32

#: The opener of every generated multi-line lambda action.
LAMBDA = "      - lambda: |-"
#: A script's two fixed lines. `restart` throughout: a scene re-fired while it
#: is running starts again rather than stacking a second copy on the strips.
MODE_RESTART = "    mode: restart"
THEN = "    then:"
SCRIPT_HEAD = (MODE_RESTART, THEN)


def chunked(sid: str, items: list[list[str]], loop: bool) -> list[str]:
    """Lay `items` (one YAML list item each) out as head + continuations."""
    step = CHUNK - 1  # room for the chaining execute
    starts = list(range(0, max(len(items), 1), step))
    out: list[str] = []
    for k, lo in enumerate(starts):
        last = k == len(starts) - 1
        out.append(f"  - id: {'scene_' + sid if k == 0 else f'cont_{sid}_{k}'}")
        out.extend(SCRIPT_HEAD)
        for item in items[lo : lo + step]:
            out.extend(item)
        if not last:
            out.append(f"      - script.execute: cont_{sid}_{k + 1}")
        elif loop:
            out.append(f"      - script.execute: scene_{sid}")
        out.append("")
    return out


def emit_scene(
    scene: dict[str, Any],
    zones: list[dict[str, Any]],
    idx: int,
    markers: dict[str, Any],
) -> list[str]:
    zone_ids = [z["id"] for z in zones]
    sid = scene["id"]
    lines: list[str] = [
        f"  # ── {scene['name']} ({scene['kind']}) "
        + "─" * max(0, 42 - len(scene["name"]))
    ]

    # Body actions, one YAML list item each; `chunked` lays them out.
    items: list[list[str]] = []

    def a(line: str) -> None:
        """Start a new action item (a `      - ` line) or extend the last."""
        if line.startswith("      - "):
            items.append([line])
        else:
            items[-1].append(line)

    a(f"      - logger.log: 'scene {sid}'")
    # Everyone downstream — the web page's chip, Home Assistant, the tools —
    # learns what is running from this one sensor.
    a("      - text_sensor.template.publish:")
    a("          id: current_scene")
    a(f"          state: '{sid}'")

    # Reset to the scene's base state, so a scene always starts known-good
    # even if it interrupted another mid-cue — including flash colour and
    # decay, which the previous scene's strikes may have recoloured.
    levels = scene.get("levels") or {}
    zdetail = scene.get("zones") or {}

    def zone_sets(i: int, z: str) -> str:
        d = zdetail.get(z) or {}
        center = eff_id(d["center"], sid) if d.get("center") else -1
        ov = OVERLAY_IDS.get(d.get("overlay", "none"), 0)
        pal = PALETTE_IDS.get(d.get("palette", "haunt"), 0)
        phase = float(d.get("phase", 0.0))
        return (
            f"id(zone_effect)[{i}] = {eff_id(scene['base'].get(z, 'off'), sid)};"
            f" id(zone_flash)[{i}] = 0.0f;"
            f" id(zone_flash_target)[{i}] = 0.0f;"
            f" id(zone_flash_decay)[{i}] = {DEFAULT_DECAY}f;"
            f" id(zone_level)[{i}] = {float(levels.get(z, 1.0)):.2f}f;"
            f" id(zone_center)[{i}] = {center};"
            f" id(zone_overlay)[{i}] = {ov};"
            f" id(zone_palette)[{i}] = {pal};"
            f" id(zone_phase)[{i}] = {phase:.2f}f;"
            f" id(zone_flash_mode)[{i}] = 0;"
            + "".join(f" id(zone_flash_col)[{i * 4 + k}] = 1.0f;" for k in range(4))
        )

    sets = " ".join(zone_sets(i, z) for i, z in enumerate(zone_ids))
    a(f"      - lambda: '{sets}'")
    # The scene's own level — unless the desk has hushed the porch (sound
    # routed to the Mac): then the amp stays at 0 however many scenes start.
    # A lambda rather than `media_player.volume_set: !lambda` so the file
    # stays plain YAML for every tool that loads it with safe_load.
    a(LAMBDA)
    a("          auto call = id(castle_media)->make_call();")
    a(
        f"          call.set_volume(id(speaker_hush) ? 0.0f : {float(scene.get('volume', 0.8))}f);"
    )
    a("          call.perform();")
    # Audio goes through the generated `sfx` dispatch script rather than a
    # direct play action, because the two builds implement it differently:
    # the flash build plays the embedded file, the SD build streams the same
    # track off the card (see audio_flash.yaml / audio_sd.yaml below).
    a("      - script.execute:")
    a("          id: sfx")
    a(f"          track: '{idx:02d}_{sid}'")

    prev = 0
    pulses = pulse_cues(scene, markers)
    kept = thin_pulses(pulses)
    if len(kept) < len(pulses):
        print(
            f"note: scene {scene['id']}: {len(pulses)} pulse hits thinned to "
            f"{len(kept)} (PULSE_CAP — device RAM; preview matches)"
        )
    all_cues = (scene.get("cues") or []) + kept
    for cue in sorted(all_cues, key=lambda c: c["t"]):
        dt = cue["t"] - prev
        if dt > 0:
            a(f"      - delay: {dt}ms")
            prev = cue["t"]
        note = f"    # {cue['note']}" if cue.get("note") else ""
        if cue["op"] == "set":
            i = zone_ids.index(cue["zone"])
            stmt = f"id(zone_effect)[{i}] = {eff_id(cue['effect'], sid)};"
            if "level" in cue:
                stmt += f" id(zone_level)[{i}] = {float(cue['level']):.2f}f;"
            a(f"      - lambda: '{stmt}'{note}")
        elif cue["op"] == "strike":
            targets = (
                cue.get("targets")
                or ([cue["zone"]] if cue.get("zone") else None)
                or zone_ids
            )
            # `ms` documents the intended visual length; the actual fall is
            # the per-zone decay factor, applied every frame in the render
            # loop. Colour is per strike: lightning white, heartbeat red.
            amt = float(cue.get("intensity", 1.0))
            col = cue.get("color", WHITE)
            dec = float(cue.get("decay", DEFAULT_DECAY))
            mode = FLASH_MODE_IDS.get(cue.get("pixels", "all"), 0)
            attack = int(cue.get("attack", 0))
            parts = []
            for z in targets:
                i = zone_ids.index(z)
                if attack > 0:
                    # #10: swell to the peak over `attack` ms — the render
                    # loop climbs by _rise per 16 ms frame, then decays.
                    parts.append(f"id(zone_flash_target)[{i}] = {amt:.3f}f;")
                    parts.append(
                        f"id(zone_flash_rise)[{i}] = {amt * 16.0 / attack:.4f}f;"
                    )
                else:
                    parts.append(f"id(zone_flash)[{i}] = {amt:.3f}f;")
                    parts.append(f"id(zone_flash_target)[{i}] = 0.0f;")
                parts.append(f"id(zone_flash_decay)[{i}] = {dec}f;")
                # Mask + epoch: WHERE on the jewel this strike lands, and a
                # fresh scatter subset each time (mirrors fireCues in show.ts).
                parts.append(f"id(zone_flash_mode)[{i}] = {mode};")
                parts.append(
                    f"id(zone_flash_epoch)[{i}] = (id(zone_flash_epoch)[{i}] + 1) % 1000;"
                )
                parts += [
                    f"id(zone_flash_col)[{i * 4 + k}] = {float(col[k]):.2f}f;"
                    for k in range(4)
                ]
            a(f"      - lambda: '{' '.join(parts)}'{note}")
        else:
            raise SystemExit(f"scene {sid}: unknown cue op {cue['op']!r}")

    tail = scene["duration_ms"] - prev
    if tail > 0:
        a(f"      - delay: {tail}ms")
    lines.extend(chunked(sid, items, bool(scene.get("loop"))))
    return lines


def main() -> int:
    doc = yaml.safe_load(SRC.read_text())
    zones = doc["zones"]
    per = doc["hardware"]["pixels_per_zone"]
    # A zone may now name its own fixture; `pixels_per_zone` is the fallback
    # for one that does not, which is what keeps an unedited scenes.yaml
    # building. See tools/rig_layout.py.
    layouts = zone_layouts(zones, per)
    total = sum(layouts[z["id"]].n for z in zones)

    out = [HEADER, ""]
    out.append(f"# {len(zones)} zones, {total} pixels — one strip each")
    for zid, (lo, hi) in zone_pixels(layouts, zones).items():
        out.append(f"#   {zid:<8} {layouts[zid].n:>2} px (chain equivalent {lo}-{hi})")
    out.append("")
    out.append("script:")

    markers = json.loads(MARKERS.read_text()) if MARKERS.exists() else {}
    if not markers:
        print("note: no audio/markers.json — run `make audio` first; no beat pulses")
    # The same checks the studio runs before a splice (scene_schema), so a
    # hand-edited scenes.yaml fails here with every problem listed, not one
    # SystemExit per rebuild.
    zone_ids = [z["id"] for z in zones]
    for scene in doc["scenes"]:
        problems = validate_scene(scene, zone_ids)
        if problems:
            sid = scene.get("id", "?") if isinstance(scene, dict) else "?"
            raise SystemExit(f"scene {sid}: " + "\n  ".join(problems))
    # hardware.audio.max_volume caps every scene's level (scenes.yaml says
    # why); the firmware's /api/volume clamps to the same number via rig.h.
    cap = float(doc["hardware"].get("audio", {}).get("max_volume", 1.0))
    for scene in doc["scenes"]:
        scene["volume"] = min(float(scene.get("volume", 0.8)), cap)
    script_ids: list[str] = []  # every scene script, continuations too
    for i, scene in enumerate(doc["scenes"], start=1):
        lines = emit_scene(scene, zones, i, markers)
        script_ids += [
            ln[len("  - id: ") :] for ln in lines if ln.startswith("  - id: ")
        ]
        out.extend(lines)

    # A single stop script, so "blackout" is one call from anywhere.
    #
    # It clears the whole per-zone texture, not just the base effect. The
    # render loop draws the centre pixel from zone_center whenever that is
    # set, and composites the overlay on top of whatever the base is — so a
    # stop that only zeroed zone_effect left vigil's centre embers burning
    # and the door still sparkling, on a castle that was supposed to be dark
    # (tests/cxx/render_check.cpp shows sparkle/meteor/chase all ADD light
    # to a black base). A pending strike swell is cancelled for the same
    # reason: it would otherwise climb, then fall, after the stop.
    out.append("  # ── Blackout ─────────────────────────────────────")
    out.append("  - id: scene_stop")
    out.extend(SCRIPT_HEAD)
    stop = " ".join(
        f"id(zone_effect)[{i}] = 0; id(zone_center)[{i}] = -1;"
        f" id(zone_overlay)[{i}] = 0; id(zone_flash)[{i}] = 0.0f;"
        f" id(zone_flash_target)[{i}] = 0.0f;"
        for i in range(len(zones))
    )
    out.append(f"      - lambda: '{stop}'")
    # And it stops the scene SCRIPTS, not only their output. Until v5.35 it
    # did not: a looping scene's pending delay survived the stop, re-fired
    # within 30 s, and Vigil walked back on — volume, lights and its wind
    # track — under whatever the operator was doing (every "quiet board"
    # test in docs/ISSUE-ring-flicker.md had it playing underneath).
    out.append(LAMBDA)
    out.extend(f"          id({sid})->stop();" for sid in script_ids)
    out.append("      - media_player.stop:")
    out.append("      - text_sensor.template.publish:")
    out.append("          id: current_scene")
    out.append("          state: 'stop'")
    out.append("      - text_sensor.template.publish:")
    out.append("          id: current_track")
    out.append("          state: ''")
    out.append("")

    # Scene dispatch by NAME, for every caller that only has a string: the
    # web server's /api/scene, the PIR's configurable scene select, tools.
    # Generated so a new scene is automatically reachable everywhere.
    out.append("  # ── Dispatch by name ─────────────────────────────")
    out.append("  - id: run_scene")
    out.append(MODE_RESTART)
    out.append("    parameters:")
    out.append("      scene: string")
    out.append(THEN)
    out.append(LAMBDA)
    out.append("          // Stop every scene script first. Without this a looping")
    out.append("          // scene's pending delay re-fires AFTER the new scene starts")
    out.append("          // and takes the stage back — two loops fighting forever.")
    out.append("          // Continuations too (cont_*): a scene is several short")
    out.append(
        "          // scripts, see CHUNK — the one mid-delay may be any of them."
    )
    out.extend(f"          id({sid})->stop();" for sid in script_ids)
    for j, scene in enumerate(doc["scenes"]):
        kw = "if" if j == 0 else "else if"
        out.append(
            f'          {kw} (scene == "{scene["id"]}") '
            f"id(scene_{scene['id']})->execute();"
        )
    out.append('          else if (scene == "stop") id(scene_stop)->execute();')
    # "halt": the stops above and nothing else — lights keep their texture,
    # audio is untouched. /api/play runs it first so a looping scene's 30 s
    # re-fire cannot take the speakers back from the file the operator chose
    # (a song, the panel's speaker test). A branch here rather than its own
    # script: a script is a static object, and the S2's dram0 is on a diet.
    out.append('          else if (scene == "halt") {}')
    out.append(
        '          else ESP_LOGW("castle", "unknown scene \'%s\'", scene.c_str());'
    )
    out.append("")
    out.extend(emit_show_playlist(doc))

    # Show-state sensors and the PIR's configuration entities. Generated here
    # because the scene list is: the PIR select's options ARE the scenes.
    scene_ids = [s["id"] for s in doc["scenes"]]
    pir_default = "approach" if "approach" in scene_ids else scene_ids[0]
    out += [
        "text_sensor:",
        "  - platform: template",
        "    id: current_scene",
        "    name: 'Current scene'",
        "  - platform: template",
        "    id: current_track",
        "    name: 'Current track'",
        "",
        "# Motion is configuration, not code: which scene fires, how long the",
        "# lockout is, and whether the sensor is armed at all — all changeable",
        "# from the web panel or Home Assistant, all persisted.",
        "select:",
        "  - platform: template",
        "    name: 'PIR scene'",
        "    id: pir_scene",
        "    optimistic: true",
        "    restore_value: true",
        f"    options: [{', '.join(scene_ids)}, stop]",
        f"    initial_option: {pir_default}",
        "number:",
        "  - platform: template",
        "    name: 'PIR cooldown'",
        "    id: pir_cooldown",
        "    optimistic: true",
        "    restore_value: true",
        "    min_value: 5",
        "    max_value: 600",
        "    step: 5",
        "    initial_value: 60",
        "    unit_of_measurement: s",
        "switch:",
        "  - platform: template",
        "    name: 'PIR armed'",
        "    id: pir_armed",
        "    optimistic: true",
        "    restore_mode: RESTORE_DEFAULT_ON",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))

    # The media manifest and both sfx implementations moved to
    # gen_esphome_audio.py (the 500-line cap; the seam is honest — nothing
    # about cues, everything about which bytes play and from where).
    MEDIA_OUT.write_text(ga.emit_media_files(doc))
    AUDIO_FLASH.write_text(ga.emit_audio_flash(doc))
    AUDIO_SD.write_text(ga.emit_audio_sd(doc))

    n_cues = sum(len(s.get("cues") or []) for s in doc["scenes"])
    # Geometry the firmware indexes, and the strips that use it. Written
    # from the same `layouts` the cue scripts above were emitted against, so
    # a zone can never end up with cues aimed at pixels its strip lacks.
    RIG_OUT.write_text(emit_rig_header(layouts, zones, round(cap * 100)))
    LIGHTS_OUT.write_text(emit_lights(layouts, zones, per))

    print(
        f"wrote {bp.rel(OUT)} + {MEDIA_OUT.name} + {RIG_OUT.name} + {LIGHTS_OUT.name}"
    )
    print(f"  {len(doc['scenes'])} scenes, {n_cues} cues, {total} pixels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
