#!/usr/bin/env python3
"""Bake a 1-bit bitmap font for the eInk status screen.

Hand-typing a 96-glyph font table is a typo generator with no test — a wrong
byte is a wrong pixel in one letter, found only by squinting at a porch. So
the table is rasterised from Menlo (macOS's fixed-width system font) at 10 px
instead, and the header carries its cell size for the driver to consume.
The header is committed, so the build does not depend on the font existing.

    tools/gen_eink_font.py    ->  firmware/generated/eink_font.h
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware" / "generated" / "eink_font.h"

FIRST, LAST = 32, 126  # printable ASCII


def main() -> int:
    font = ImageFont.truetype("/System/Library/Fonts/Menlo.ttc", 10)
    widths = {int(font.getlength(chr(c))) for c in range(FIRST, LAST + 1)}
    if len(widths) != 1:
        raise SystemExit(f"font is not fixed-width: advances {sorted(widths)}")
    cw = widths.pop()
    ascent, descent = font.getmetrics()
    ch = ascent + descent

    lines = []
    for c in range(FIRST, LAST + 1):
        img = Image.new("1", (cw, ch), 0)
        ImageDraw.Draw(img).text((0, 0), chr(c), font=font, fill=1)
        px = img.load()
        rows = []
        for y in range(ch):
            b = 0
            for x in range(cw):
                if px[x, y]:
                    b |= 0x80 >> x
            rows.append(f"0x{b:02x}")
        name = chr(c).replace("\\", "backslash") if c in (0x5C,) else chr(c)
        lines.append(f"    {', '.join(rows)},  // '{name}'")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "#pragma once\n"
        "// Generated by tools/gen_eink_font.py — do not edit.\n"
        "#include <cstdint>\n\n"
        "namespace castle_font {\n"
        f"inline constexpr int W = {cw};\n"
        f"inline constexpr int H = {ch};\n"
        f"inline constexpr int FIRST = {FIRST};\n"
        f"inline constexpr int LAST = {LAST};\n"
        "// One byte per row (MSB-first), H rows per glyph.\n"
        "inline constexpr uint8_t GLYPHS[] = {\n"
        + "\n".join(lines)
        + "\n};\n"
        "}  // namespace castle_font\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {cw}x{ch} cells, "
          f"{LAST - FIRST + 1} glyphs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
