#!/usr/bin/env python3
"""The hardware half of the generator: strips, pins and fixture geometry.

Split out of gen_esphome.py, which had grown past the 500-line cap, along a
real seam rather than an arbitrary one. gen_esphome.py answers "what does the
show do" — the cue scripts, the playlist, the dispatch. This answers "what is
it doing it to" — how many pixels are in each window, which pin carries them,
and where each one sits in space.

Both are written from the same `zones:` block in scenes/scenes.yaml in one
run, which is what stops a zone ending up with cues aimed at pixels its strip
does not have.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from rig_layout import Layout


def emit_rig_header(
    layouts: dict[str, Layout],
    zones: Sequence[Mapping[str, Any]],
    max_volume_pct: int = 100,
) -> str:
    """Bake each zone's geometry into a header the firmware only indexes.

    The device does no layout arithmetic: `walk`, `fall` and `core` are the
    tables computed by rig_layout.py, which web/test/rig_parity.ts holds
    identical to the browser's. That is the whole reason there is no third
    copy of this maths in C++.
    """
    out = [
        "// GENERATED BY tools/gen_esphome.py — DO NOT EDIT",
        "//",
        "// Source of truth: scenes/scenes.yaml (the `zones:` block)",
        "// Regenerate with:  make generate",
        "//",
        "// Fixture geometry per zone. See castle_effects.h for what the",
        "// fields mean and tools/rig_layout.py for how they are derived.",
        "#pragma once",
        "",
        '// Flat, not "../castle_effects.h": ESPHome\'s `includes:` copies each',
        "// file into the build's src/ by BASENAME, so the directory this lives",
        "// in does not survive to the compiler (esphome/core/config.py,",
        "// add_includes).",
        '#include "castle_effects.h"',
        "",
        "namespace castle {",
        "// The loudest the amps may be asked for — scenes.yaml's",
        "// hardware.audio.max_volume. /api/volume clamps to it; every",
        "// scene's level was generated under it.",
        f"inline constexpr int kMaxVolumePct = {max_volume_pct};",
        "",
        "namespace rig_tables {",
        "",
    ]

    def arr(kind: str, zid: str, vals: list[str]) -> None:
        # A zero-length array is ill-formed in C++, and an empty zone is a
        # real configuration (nothing wired to that channel yet), so unwired
        # zones get one dead element that `n = 0` stops anything reading.
        ctype = "bool" if kind == "core" else "float"
        dead = "false" if kind == "core" else "0.0f"
        body = ", ".join(vals) if vals else dead
        out.append(f"inline constexpr {ctype} {zid}_{kind}[] = {{{body}}};")

    for z in zones:
        zid = z["id"]
        lay = layouts[zid]
        out.append(f"// {zid}: {z.get('fixture', 'uniform')}, {lay.n} pixels")
        arr("walk", zid, [f"{v:.6f}f" for v in lay.walk])
        arr("fall", zid, [f"{v:.6f}f" for v in lay.fall])
        arr("core", zid, ["true" if v else "false" for v in lay.core])
        out.append("")

    out.append("}  // namespace rig_tables")
    out.append("")
    out.append("// Indexed by zone number, matching the order of `zones:` in")
    out.append("// scenes.yaml and the zone_* globals in castle.yaml.")
    out.append(f"inline constexpr Fixture RIG[{len(zones)}] = {{")
    for z in zones:
        zid = z["id"]
        lay = layouts[zid]
        center = -1 if lay.center is None else lay.center
        out.append(
            f"    {{{lay.n}, {center}, {lay.fall_steps}, rig_tables::{zid}_walk,"
            f" rig_tables::{zid}_fall, rig_tables::{zid}_core}},  // {zid}"
        )
    out.append("};")
    out.append("")
    biggest = max((layouts[z["id"]].n for z in zones), default=0)
    out.append("// The frame buffer one lambda needs, four bytes per pixel.")
    out.append(f"inline constexpr int RIG_MAX_PIXELS = {max(1, biggest)};")
    out.append("")
    out.append("}  // namespace castle")
    return "\n".join(out) + "\n"


# ── Bench patterns ────────────────────────────────────────────────────
# Three test effects on every strip, driven by /api/light?c=<zone>:<name>
# and the desk's strip-test row. A solid colour answers "is this line
# alive"; these answer the questions that come next — how many pixels
# arrive, in what order, with which colour first, and where a chain dies.
# Deliberately NO static buffers (the Show effect's `buf` is the only one
# worth the static RAM — a rule the S2's 20 bytes of dram0 headroom made
# absolute and the S3 keeps out of habit, since these draw nothing from a
# buffer anyway) and no scene state: they draw from `it` and millis() alone,
# so they are safe to leave running while you go and look.
#: How every strip effect starts. Four of them, so it is written once.
EFFECT = "      - addressable_lambda:"
#: And the line that opens each one's body, for the same reason.
LAMBDA_BODY = "          lambda: |-"

TEST_EFFECTS = [
    EFFECT,
    '          name: "Test Bars"',
    "          update_interval: 500ms",
    LAMBDA_BODY,
    "            // Red, green, blue repeating. Wrong first colour means",
    "            // channel_colors is wrong; a gap means a dead pixel;",
    "            // count the triplets to see how many pixels arrive.",
    "            for (int p = 0; p < it.size(); p++) {",
    "              const int k = p % 3;",
    "              it[p] = Color(k == 0 ? 255 : 0, k == 1 ? 255 : 0,",
    "                            k == 2 ? 255 : 0, 0);",
    "            }",
    EFFECT,
    '          name: "Test Chase"',
    "          update_interval: 100ms",
    LAMBDA_BODY,
    "            // One white dot walking the chain, ~4 px/s. Where it stops",
    "            // is where the data stops: a cut wire, a cold joint, or the",
    "            // pixel that died. It wraps, so watch one full lap.",
    "            const int n = it.size() > 0 ? it.size() : 1;",
    "            const int at = (millis() / 250) % n;",
    "            for (int p = 0; p < it.size(); p++)",
    "              it[p] = p == at ? Color(255, 255, 255, 255) : Color(0, 0, 0, 0);",
    EFFECT,
    '          name: "Test Ends"',
    "          update_interval: 500ms",
    LAMBDA_BODY,
    "            // First pixel red, last blue, the rest dim. Which end lights",
    "            // red is the end the data goes in — the answer when a jewel",
    "            // is mounted upside down and the centre pixel looks wrong.",
    "            for (int p = 0; p < it.size(); p++)",
    "              it[p] = Color(24, 24, 24, 0);",
    "            if (it.size() > 0) it[0] = Color(255, 0, 0, 0);",
    "            if (it.size() > 1) it[it.size() - 1] = Color(0, 0, 255, 0);",
]


# The RMT peripheral is a budget, and the budget is per CHIP.
#
# On the ESP32-S3: SOC_RMT_MEM_WORDS_PER_CHANNEL is 48, and of the eight
# channels per group four are TX-capable — 192 symbols of TX memory in total,
# no DMA in the path this driver uses (soc_caps.h; docs/V5-SPEC.md §13.4). A
# channel that asks for more than a block takes the next channel's, which is
# how ESPHome's old 192-symbol-per-strip default left strips 2 and 3 dead
# (bench-diagnosed 2026-08-19 on the S2, whose blocks were 64). A bigger
# block is not a luxury either: the refill ISR must top the block up every
# half-block — 24 symbols is 30 us of WS2812 bits — and a late refill is a
# garbled pixel.
#
# HISTORY, and the reason `Chip` exists at all: until 2026-09-17 the porch
# board was an ESP32-S2, whose RMT is 4 channels of 64 symbols — 256, and NOT
# interchangeable with the numbers above. Asking an S3 for 64 is not "a bit
# generous", it is not a whole block, and it fails the same quiet way. The
# generator wrote the S2's strips and then a second, generated package of
# `!extend`s that re-spent each block in S3 units; both are gone with the S2,
# and the only difference left between this repo's two builds is the
# RESERVATION below, not the block size.
class Chip:
    """One chip's RMT arithmetic: the block size and how many there are.

    One instance is left (S3). The class stays because the numbers it holds
    are the kind that get inherited by assumption: a future chip gets an
    entry and every arithmetic below follows it, rather than 48 and 192
    being sprinkled through the emitters.
    """

    def __init__(self, name: str, block: int, channels: int) -> None:
        self.name = name
        self.block = block
        self.channels = channels
        self.total = block * channels

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"Chip({self.name!r}, block={self.block}, total={self.total})"


#: The only chip this repo builds for: the Feather #5477 in the yard and the
#: WROOM-1 carrier board, which have the same RMT (docs/V5-SPEC.md §13.4).
S3 = Chip("ESP32-S3", 48, 4)
#: Keyed by the ESPHome `variant:` spelling, so a target names its chip the
#: same way its YAML does.
CHIPS = {"esp32s3": S3}

#: The one budget, as module constants: what a caller with no opinion gets.
RMT_TOTAL_SYMBOLS = S3.total
RMT_BLOCK = S3.block
#: The fourth consumer, and the one this file does not write:
#: castle_feather_s3.yaml declares a `status_pixel` on GPIO33 with
#: `rmt_symbols: 48` by hand, because it is the Feather's own LED rather than
#: part of the rig. The budget below has to be TOLD about it — until
#: 2026-09-06 it was not, and the generator would hand out a block that was
#: already gone while printing a banner that said so (grade report 2026-09-06
#: J2). The WROOM-1 carrier has no such LED and reserves nothing, which is
#: why the banner emit_lights writes states BOTH builds' totals
#: (grade report 2026-09-17 J6) — one generated file is read by two builds
#: that spend different amounts of the same peripheral.
STATUS_PIXEL_BLOCKS = 1


def rmt_blocks(z: Mapping[str, Any]) -> int:
    """How many whole channel blocks a zone asks for.

    A zone states its appetite in symbols (`rmt_symbols: 96` is two blocks),
    which is the spelling scenes.yaml has always used and the number the
    build literally emits. Blocks are what the request MEANS, though: the
    hardware has no finer granularity. No zone declares this today — they all
    take the default of one block — so the multiple-of-48 rule exists to
    catch a hand-edit, in particular an S2-era 64 pasted back in.
    """
    n = int(z.get("rmt_symbols", S3.block))
    if n % S3.block or n < S3.block:
        raise SystemExit(
            f"zone {z['id']}: rmt_symbols must be a multiple of "
            f"{S3.block} (the {S3.name} allocates whole blocks), got {n}"
        )
    return n // S3.block


def rmt_symbols(z: Mapping[str, Any], chip: Chip = S3) -> int:
    """A zone's RMT memory on `chip`. Whole blocks only — the hardware has no
    other granularity — and the longest strip is the one worth spending on."""
    return rmt_blocks(z) * chip.block


def check_rmt_budget(
    zones: Sequence[Mapping[str, Any]],
    layouts: dict[str, Layout],
    chip: Chip = S3,
    reserved_blocks: int = 0,
) -> int:
    """Spend no more than the peripheral has; return what is genuinely free.

    `reserved_blocks` is what the BUILD spends outside the strips written
    here — on the Feather the status pixel's one block, on the WROOM carrier
    nothing. A reservation that is not counted is worse than no budget at
    all: the caller reads "0 block(s) spare" and the peripheral has already
    been oversubscribed by a strip that will simply stay dark.
    """
    live = [z for z in zones if layouts[z["id"]].n > 0]
    strips = sum(rmt_symbols(z, chip) for z in live)
    reserved = reserved_blocks * chip.block
    if strips + reserved > chip.total:
        held = (
            f" and the status pixel holds {reserved} more "
            f"(castle_feather_s3.yaml `status_pixel`)"
            if reserved
            else ""
        )
        raise SystemExit(
            f"RMT budget: {len(live)} strips ask for {strips} symbols{held}, "
            f"but the {chip.name} has {chip.total}. Strips past the limit get "
            f"no channel and stay dark. Lower a zone's rmt_symbols."
        )
    return chip.total - strips - reserved


def channel_colors(zone: Mapping[str, Any]) -> str:
    """The word a zone's strip clocks out, e.g. "GRB" or "GRBW".

    ESPHome's `channel_colors` replaced the `rgb_order` + `is_rgbw` pair
    (deprecated, removed in 2027.3), and this is exactly the fold its own
    migration performs: the white die, when the fixture has one, goes on the
    end. Both the generated strip's substitution and castle.yaml's value for
    it come from here, so the two cannot say different things.
    """
    order = str(zone.get("rgb_order", "GRB")).upper()
    return f"{order}W" if bool(zone.get("rgbw", True)) else order


def emit_lights(
    layouts: dict[str, Layout], zones: Sequence[Mapping[str, Any]], per: int
) -> str:
    """One `light:` component per zone, each rendering itself.

    A strip per zone rather than one chain, because an RGBW fixture and an
    RGB one cannot share a data line — 32 bits per pixel against 24, and the
    channel order is per component. Three pins also mean swapping one fixture
    renumbers nothing else. docs/WIRING.md §1 and §2.

    Colour order and colour type are ONE key: `channel_colors`, the string
    the strip clocks out ("GRB", "GRBW"). ESPHome deprecated the old
    `rgb_order` + `is_rgbw` pair for removal in 2027.3, and folds them into
    exactly this string with a warning until then. The zone's substitution
    (`channels_<id>`) therefore carries the whole word, so bench.yaml can
    still repoint a zone at a plain-RGB onboard pixel without editing this
    generated file.
    """
    out = [
        "# GENERATED BY tools/gen_esphome.py — DO NOT EDIT",
        "#",
        "# Source of truth: scenes/scenes.yaml (the `zones:` block)",
        "# Regenerate with:  make generate",
        "#",
        "# One strip per zone. Pin, count and colour type all come from the",
        "# zone's own entry; substitutions let bench.yaml point a zone at the",
        "# onboard pixel without editing this file.",
        "light:",
    ]
    for zi, z in enumerate(zones):
        zid = z["id"]
        lay = layouts[zid]
        if lay.n == 0:
            out.append(f"  # {zid}: nothing wired — no strip emitted.")
            continue
        pin = z.get("pin", 18)
        chan = channel_colors(z)
        out += [
            "  - platform: esp32_rmt_led_strip",
            f"    id: zone_{zid}",
            f'    name: "Castle {zid}"',
            f"    pin: GPIO${{pin_{zid}}}",
            f"    num_leds: ${{px_{zid}}}",
            "    chipset: WS2812",
            f"    channel_colors: ${{channels_{zid}}}",
            # Explicit, and budgeted: see RMT_TOTAL_SYMBOLS above for why a
            # per-strip default bigger than one block leaves the strips after
            # the first dark, and why a long strip may be worth a second.
            f"    rmt_symbols: {rmt_symbols(z)}",
            # Internal RAM, deliberately: the strip buffer is under 50 bytes,
            # and the RMT refill ISR must be able to read it during flash-cache
            # blackouts. PSRAM there truncated frames at 4 px on every strip
            # after the first (bench-diagnosed 2026-08-19).
            "    use_psram: false",
            "    default_transition_length: 0s",
            "    effects:",
            EFFECT,
            '          name: "Show"',
            "          update_interval: 16ms",
            LAMBDA_BODY,
            "            using namespace castle;",
            f"            const Fixture &fx = RIG[{zi}];",
            "            static uint8_t buf[RIG_MAX_PIXELS * 4];",
            "            ZoneIo io{",
            f"                &id(zone_flash)[{zi}], &id(zone_flash_target)[{zi}],",
            f"                &id(zone_flash_rise)[{zi}], id(zone_flash_decay)[{zi}],",
            f"                &id(zone_flash_col)[{zi * 4}],",
            f"                id(zone_level)[{zi}], id(zone_phase)[{zi}],",
            f"                (float) id(trim_{zid.lower()}).state,",
            "                (float) id(hue_balance).state,",
            f"                id(zone_effect)[{zi}], id(zone_center)[{zi}],",
            f"                id(zone_overlay)[{zi}], id(zone_palette)[{zi}],",
            f"                id(zone_flash_mode)[{zi}], id(zone_flash_epoch)[{zi}],",
            "                id(soften).state};",
            "            step_flash(io);",
            "            render_zone(buf, %d, fx, millis() / 1000.0f, io);" % zi,
            "            for (int p = 0; p < fx.n; p++)",
            "              it[p] = Color(buf[p * 4], buf[p * 4 + 1],",
            "                            buf[p * 4 + 2], buf[p * 4 + 3]);",
            *TEST_EFFECTS,
        ]
        out.append(
            f"    # {zid}: {z.get('fixture', f'{per} uniform')} "
            f"— {lay.n} px, {chan}, GPIO{pin}"
        )

    # One override for all the strips at once. The web remote and the boot
    # sequence want to talk to "the pixels", and with a strip per zone that is
    # no longer a single `id()`. Generated rather than hand-written in the
    # show build so the zone list stays in exactly one place.
    #
    # The banner says what BOTH builds that read this file spend, because they
    # do not spend the same amount: the Feather's own status pixel holds a
    # fourth block and the WROOM-1 carrier has no such LED (grade report
    # 2026-09-17 J6). One number here would have been false for one of them,
    # which is the failure mode that made the reservation visible in the first
    # place (grade report 2026-09-06 J2).
    feather_spare = check_rmt_budget(
        zones, layouts, reserved_blocks=STATUS_PIXEL_BLOCKS
    )
    carrier_spare = check_rmt_budget(zones, layouts)
    live = [z["id"] for z in zones if layouts[z["id"]].n > 0]
    out.append(
        f"# RMT, the Feather build (castle_feather_s3.yaml): "
        f"{RMT_TOTAL_SYMBOLS - feather_spare} of {RMT_TOTAL_SYMBOLS} symbols "
        f"spent — {len(live)} strip(s) of {RMT_BLOCK} and the status pixel "
        f"({STATUS_PIXEL_BLOCKS} block) — {feather_spare // RMT_BLOCK} "
        f"block(s) spare."
    )
    out.append(
        f"# RMT, the carrier build (castle_s3.yaml), which has no status "
        f"pixel: {RMT_TOTAL_SYMBOLS - carrier_spare} of "
        f"{RMT_TOTAL_SYMBOLS} — {carrier_spare // RMT_BLOCK} block(s) spare."
    )
    zone_rgbw = {z["id"]: bool(z.get("rgbw", True)) for z in zones}
    out += [
        "",
        "script:",
        "  - id: lights_override",
        "    mode: restart",
        "    parameters:",
        "      arg: string",
        "    then:",
        "      - lambda: |-",
        "          esphome::light::LightState *zones[] = {"
        + ", ".join(f"id(zone_{z})" for z in live)
        + "};",
        "          const char *names[] = {" + ", ".join(f'"{z}"' for z in live) + "};",
        "          const bool rgbw[] = {"
        + ", ".join(str(bool(zone_rgbw[z])).lower() for z in live)
        + "};",
        '          // "[zone:]spec[@pct]": spec = RRGGBB | white | off | show; one',
        "          // strip when a zone is named (the desk's channel test), pct 1..100.",
        "          std::string spec = arg, only;",
        "          const auto colon = arg.find(':');",
        "          if (colon != std::string::npos) {",
        "            only = arg.substr(0, colon); spec = arg.substr(colon + 1);",
        "          }",
        "          float bright = 1.0f;",
        "          const auto at = spec.find('@');",
        "          if (at != std::string::npos) {",
        "            bright = atoi(spec.c_str() + at + 1) / 100.0f; spec.resize(at);",
        "          }",
        f"          for (size_t i = 0; i < {len(live)}; i++) {{",
        "            if (!only.empty() && only != names[i]) continue;",
        "            auto *z = zones[i];",
        '            if (spec == "off") { z->turn_off().perform(); continue; }',
        "            auto call = z->turn_on();",
        "            call.set_brightness(bright);",
        '            if (spec == "show") {',
        '              call.set_effect("Show");',
        '            } else if (spec == "bars" || spec == "chase" || spec == "ends") {',
        "              // The bench patterns, one effect each (TEST_EFFECTS).",
        '              call.set_effect(spec == "bars" ? "Test Bars"',
        '                              : spec == "chase" ? "Test Chase" : "Test Ends");',
        '            } else if (spec == "white") {',
        "              // The white LED itself on an RGBW fixture; an RGB one",
        "              // mixes it. Tests the one channel a colour never lights.",
        '              call.set_effect("None");',
        "              if (rgbw[i]) call.set_rgbw(0.0f, 0.0f, 0.0f, 1.0f);",
        "              else call.set_rgb(1.0f, 1.0f, 1.0f);",
        "            } else {",
        "              // Park on a colour, no animation. White channel OFF:",
        "              // left alone it kept whatever the effect last wrote,",
        "              // and 'red' came out pink on the jewels (2026-08-21).",
        "              long v = strtol(spec.c_str(), nullptr, 16);",
        '              call.set_effect("None");',
        "              call.set_rgbw(((v >> 16) & 0xFF) / 255.0f,",
        "                            ((v >> 8) & 0xFF) / 255.0f,",
        "                            (v & 0xFF) / 255.0f, 0.0f);",
        "            }",
        "            call.perform();",
        "          }",
    ]
    return "\n".join(out) + "\n"
