#!/usr/bin/env python3
"""Generate the ESPHome scene scripts from scenes.yaml.

Hand-writing these would mean the cue timings in the previewer and the cue
timings on the device drift apart within a week. They come from one file
instead.

    tools/gen_esphome.py        # writes firmware/generated/scenes.yaml

Each scene becomes an ESPHome `script` that plays its audio file and then walks
the light cues as a series of delays. Cues are emitted as *deltas* between
absolute timestamps, because ESPHome scripts step forward with `delay:`.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scenes" / "scenes.yaml"
MARKERS = ROOT / "audio" / "markers.json"
OUT = ROOT / "firmware" / "generated" / "scenes.yaml"

HEADER = """# GENERATED BY tools/gen_esphome.py — DO NOT EDIT
#
# Source of truth: scenes/scenes.yaml
# Regenerate with:  make generate
#
# Each scene is a script: start its audio file, then step the light cues.
# Timings are deltas between absolute cue times from the source file.
"""

# Contract with the Effect enum in firmware/castle_effects.h. Integers rather
# than strings so the render hot path is a switch, not a string compare.
EFFECT_IDS = {
    "off": 0, "candle": 1, "ember": 2, "furnace": 3, "spirit": 4, "eyes": 5,
    "seance": 6, "wisp": 7, "mansion": 8, "chill": 9, "throb": 10, "strobe": 11,
}


def zone_pixels(zones: list[dict], per: int) -> dict[str, tuple[int, int]]:
    """Map each zone to its [first, last] index in the single pixel chain."""
    out = {}
    for i, z in enumerate(zones):
        out[z["id"]] = (i * per, (i + 1) * per - 1)
    return out


def eff_id(name: str, scene_id: str) -> int:
    if name not in EFFECT_IDS:
        raise SystemExit(f"scene {scene_id}: unknown effect {name!r}")
    return EFFECT_IDS[name]


def pulse_cues(scene: dict, markers: dict) -> list[dict]:
    """Beat markers from the audio render, turned into light pulses.

    The renderer reports the ACTUAL event times (heartbeat thumps, chord
    onsets, downbeats), so these stay locked to the audio even when a synth
    jitters its own timing. Scenes opt in with a `pulse:` block.
    """
    cfg = scene.get("pulse")
    beats = markers.get(scene["id"], [])
    if not cfg or not beats:
        return []
    return [{"t": t, "op": "strike", "zone": cfg.get("zone"),
             "intensity": cfg.get("intensity", 0.3), "note": "beat"}
            for t in beats]


def emit_scene(scene: dict, zones: list[dict], idx: int, markers: dict) -> list[str]:
    zone_ids = [z["id"] for z in zones]
    sid = scene["id"]
    lines: list[str] = []
    a = lines.append

    a(f"  # ── {scene['name']} ({scene['kind']}) " + "─" * max(0, 42 - len(scene["name"])))
    a(f"  - id: scene_{sid}")
    a("    mode: restart")
    a("    then:")
    a(f"      - logger.log: 'scene {sid}'")

    # Reset to the scene's base state, so a scene always starts known-good
    # even if it interrupted another mid-cue.
    sets = " ".join(
        f"id(zone_effect)[{i}] = {eff_id(scene['base'].get(z, 'off'), sid)};"
        f" id(zone_flash)[{i}] = 0.0f;"
        for i, z in enumerate(zone_ids)
    )
    a(f"      - lambda: '{sets}'")
    a(f"      - media_player.volume_set: {scene.get('volume', 0.8)}")
    # announcement:true because the device defines only the announcement
    # pipeline — see the comment in firmware/castle.yaml.
    a("      - media_player.speaker.play_on_device_media_file:")
    a(f"          media_file: snd_{sid}")
    a("          announcement: true")

    prev = 0
    all_cues = (scene.get("cues") or []) + pulse_cues(scene, markers)
    for cue in sorted(all_cues, key=lambda c: c["t"]):
        dt = cue["t"] - prev
        if dt > 0:
            a(f"      - delay: {dt}ms")
            prev = cue["t"]
        note = f"    # {cue['note']}" if cue.get("note") else ""
        if cue["op"] == "set":
            i = zone_ids.index(cue["zone"])
            a(f"      - lambda: 'id(zone_effect)[{i}] = "
              f"{eff_id(cue['effect'], sid)};'{note}")
        elif cue["op"] == "strike":
            targets = [cue["zone"]] if cue.get("zone") else zone_ids
            # Full intensity, matching the previewer — `ms` documents the
            # intended visual length, decay is handled in the render loop.
            amt = float(cue.get("intensity", 1.0))
            stmt = " ".join(
                f"id(zone_flash)[{zone_ids.index(z)}] = {amt:.2f}f;" for z in targets
            )
            a(f"      - lambda: '{stmt}'{note}")
        else:
            raise SystemExit(f"scene {sid}: unknown cue op {cue['op']!r}")

    tail = scene["duration_ms"] - prev
    if tail > 0:
        a(f"      - delay: {tail}ms")
    if scene.get("loop"):
        a(f"      - script.execute: scene_{sid}")
    a("")
    return lines


def main() -> int:
    doc = yaml.safe_load(SRC.read_text())
    zones = doc["zones"]
    per = doc["hardware"]["pixels_per_zone"]
    total = len(zones) * per

    out = [HEADER, ""]
    out.append(f"# {len(zones)} zones x {per} pixels = {total} in the chain")
    for zid, (lo, hi) in zone_pixels(zones, per).items():
        out.append(f"#   {zid:<8} pixels {lo}-{hi}")
    out.append("")
    out.append("script:")

    markers = json.loads(MARKERS.read_text()) if MARKERS.exists() else {}
    if not markers:
        print("note: no audio/markers.json — run `make audio` first; no beat pulses")
    for i, scene in enumerate(doc["scenes"], start=1):
        out.extend(emit_scene(scene, zones, i, markers))

    # A single stop script, so "blackout" is one call from anywhere.
    out.append("  # ── Blackout ─────────────────────────────────────")
    out.append("  - id: scene_stop")
    out.append("    mode: restart")
    out.append("    then:")
    stop = " ".join(
        f"id(zone_effect)[{i}] = 0; id(zone_flash)[{i}] = 0.0f;" for i in range(len(zones))
    )
    out.append(f"      - lambda: '{stop}'")
    out.append("      - media_player.stop:")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))

    n_cues = sum(len(s.get("cues") or []) for s in doc["scenes"])
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(doc['scenes'])} scenes, {n_cues} cues, {total} pixels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
