#!/usr/bin/env python3
"""The hardware half of the generator: strips, pins and fixture geometry.

Split out of gen_esphome.py, which had grown past the 500-line cap, along a
real seam rather than an arbitrary one. gen_esphome.py answers "what does the
show do" — the cue scripts, the playlist, the dispatch. This answers "what is
it doing it to" — how many pixels are in each window, which pin carries them,
and where each one sits in space.

Both are written from the same `zones:` block in scenes/scenes.yaml in one
run, which is what stops a zone ending up with cues aimed at pixels its strip
does not have.
"""

from __future__ import annotations

from rig_layout import Layout


def emit_rig_header(layouts: dict[str, Layout], zones: list[dict],
                    max_volume_pct: int = 100) -> str:
    """Bake each zone's geometry into a header the firmware only indexes.

    The device does no layout arithmetic: `walk`, `fall` and `core` are the
    tables computed by rig_layout.py, which web/test/rig_parity.mjs holds
    identical to the browser's. That is the whole reason there is no third
    copy of this maths in C++.
    """
    out = [
        "// GENERATED BY tools/gen_esphome.py — DO NOT EDIT",
        "//",
        "// Source of truth: scenes/scenes.yaml (the `zones:` block)",
        "// Regenerate with:  make generate",
        "//",
        "// Fixture geometry per zone. See castle_effects.h for what the",
        "// fields mean and tools/rig_layout.py for how they are derived.",
        "#pragma once",
        "",
        "// Flat, not \"../castle_effects.h\": ESPHome's `includes:` copies each",
        "// file into the build's src/ by BASENAME, so the directory this lives",
        "// in does not survive to the compiler (esphome/core/config.py,",
        "// add_includes).",
        '#include "castle_effects.h"',
        "",
        "namespace castle {",
        "// The loudest the amps may be asked for — scenes.yaml's",
        "// hardware.audio.max_volume. /api/volume clamps to it; every",
        "// scene's level was generated under it.",
        f"inline constexpr int kMaxVolumePct = {max_volume_pct};",
        "",
        "namespace rig_tables {",
        "",
    ]

    def arr(kind: str, zid: str, vals: list[str]) -> None:
        # A zero-length array is ill-formed in C++, and an empty zone is a
        # real configuration (nothing wired to that channel yet), so unwired
        # zones get one dead element that `n = 0` stops anything reading.
        body = ", ".join(vals) if vals else ("0.0f" if kind != "core" else "false")
        ctype = "bool" if kind == "core" else "float"
        out.append(f"inline constexpr {ctype} {zid}_{kind}[] = {{{body}}};")

    for z in zones:
        zid = z["id"]
        lay = layouts[zid]
        out.append(f"// {zid}: {z.get('fixture', 'uniform')}, {lay.n} pixels")
        arr("walk", zid, [f"{v:.6f}f" for v in lay.walk])
        arr("fall", zid, [f"{v:.6f}f" for v in lay.fall])
        arr("core", zid, ["true" if v else "false" for v in lay.core])
        out.append("")

    out.append("}  // namespace rig_tables")
    out.append("")
    out.append("// Indexed by zone number, matching the order of `zones:` in")
    out.append("// scenes.yaml and the zone_* globals in castle.yaml.")
    out.append(f"inline constexpr Fixture RIG[{len(zones)}] = {{")
    for z in zones:
        zid = z["id"]
        lay = layouts[zid]
        center = -1 if lay.center is None else lay.center
        out.append(
            f"    {{{lay.n}, {center}, {lay.fall_steps}, rig_tables::{zid}_walk,"
            f" rig_tables::{zid}_fall, rig_tables::{zid}_core}},  // {zid}")
    out.append("};")
    out.append("")
    biggest = max((layouts[z["id"]].n for z in zones), default=0)
    out.append("// The frame buffer one lambda needs, four bytes per pixel.")
    out.append(f"inline constexpr int RIG_MAX_PIXELS = {max(1, biggest)};")
    out.append("")
    out.append("}  // namespace castle")
    return "\n".join(out) + "\n"


# ── Bench patterns ────────────────────────────────────────────────────
# Three test effects on every strip, driven by /api/light?c=<zone>:<name>
# and the desk's strip-test row. A solid colour answers "is this line
# alive"; these answer the questions that come next — how many pixels
# arrive, in what order, with which colour first, and where a chain dies.
# Deliberately NO static buffers (the Show effect's `buf` is the only one
# the S2's dram0 can afford) and no scene state: they draw from `it` and
# millis() alone, so they are safe to leave running while you go and look.
#: How every strip effect starts. Four of them, so it is written once.
EFFECT = "      - addressable_lambda:"

TEST_EFFECTS = [
    EFFECT,
    '          name: "Test Bars"',
    "          update_interval: 500ms",
    "          lambda: |-",
    "            // Red, green, blue repeating. Wrong first colour means",
    "            // rgb_order is wrong; a gap means a dead pixel; count the",
    "            // triplets to see how many pixels actually arrive.",
    "            for (int p = 0; p < it.size(); p++) {",
    "              const int k = p % 3;",
    "              it[p] = Color(k == 0 ? 255 : 0, k == 1 ? 255 : 0,",
    "                            k == 2 ? 255 : 0, 0);",
    "            }",
    EFFECT,
    '          name: "Test Chase"',
    "          update_interval: 100ms",
    "          lambda: |-",
    "            // One white dot walking the chain, ~4 px/s. Where it stops",
    "            // is where the data stops: a cut wire, a cold joint, or the",
    "            // pixel that died. It wraps, so watch one full lap.",
    "            const int n = it.size() > 0 ? it.size() : 1;",
    "            const int at = (millis() / 250) % n;",
    "            for (int p = 0; p < it.size(); p++)",
    "              it[p] = p == at ? Color(255, 255, 255, 255) : Color(0, 0, 0, 0);",
    EFFECT,
    '          name: "Test Ends"',
    "          update_interval: 500ms",
    "          lambda: |-",
    "            // First pixel red, last blue, the rest dim. Which end lights",
    "            // red is the end the data goes in — the answer when a jewel",
    "            // is mounted upside down and the centre pixel looks wrong.",
    "            for (int p = 0; p < it.size(); p++)",
    "              it[p] = Color(24, 24, 24, 0);",
    "            if (it.size() > 0) it[0] = Color(255, 0, 0, 0);",
    "            if (it.size() > 1) it[it.size() - 1] = Color(0, 0, 255, 0);",
]


# The ESP32-S2's whole RMT peripheral: 4 channels, 64 symbols of memory each,
# 256 in total, no DMA. A channel that asks for more takes the next channel's
# block, which is how the 192-symbol default once left strips 2 and 3 dead
# (bench-diagnosed 2026-08-19). A bigger block is not a luxury either: the
# refill ISR must top the block up every half-block — 32 symbols is 40 us of
# WS2812 bits — and a late refill is a garbled pixel. So it is a budget, and
# this is where it is spent and checked. The SD build's status pixel takes one
# block, so leave RMT_BLOCK spare if it is in play (see castle_sd.yaml).
RMT_TOTAL_SYMBOLS = 256
RMT_BLOCK = 64


def rmt_symbols(z: dict) -> int:
    """A zone's RMT memory. Whole blocks only — the hardware has no other
       granularity — and the longest strip is the one worth spending on."""
    n = int(z.get("rmt_symbols", RMT_BLOCK))
    if n % RMT_BLOCK or n < RMT_BLOCK:
        raise SystemExit(f"zone {z['id']}: rmt_symbols must be a multiple of "
                         f"{RMT_BLOCK} (the S2 allocates whole blocks), got {n}")
    return n


def check_rmt_budget(zones: list[dict], layouts: dict[str, Layout]) -> int:
    """Spend no more than the peripheral has; return what is left over."""
    live = [z for z in zones if layouts[z["id"]].n > 0]
    spent = sum(rmt_symbols(z) for z in live)
    if spent > RMT_TOTAL_SYMBOLS:
        raise SystemExit(
            f"RMT budget: {len(live)} strips ask for {spent} symbols, the "
            f"ESP32-S2 has {RMT_TOTAL_SYMBOLS}. Strips past the limit get no "
            f"channel and stay dark. Lower a zone's rmt_symbols.")
    return RMT_TOTAL_SYMBOLS - spent


def emit_lights(layouts: dict[str, Layout], zones: list[dict], per: int) -> str:
    """One `light:` component per zone, each rendering itself.

    A strip per zone rather than one chain, because an RGBW fixture and an
    RGB one cannot share a data line — 32 bits per pixel against 24, and
    `is_rgbw` is per component. Three pins also mean swapping one fixture
    renumbers nothing else. docs/WIRING.md §1 and §2.
    """
    out = [
        "# GENERATED BY tools/gen_esphome.py — DO NOT EDIT",
        "#",
        "# Source of truth: scenes/scenes.yaml (the `zones:` block)",
        "# Regenerate with:  make generate",
        "#",
        "# One strip per zone. Pin, count and colour type all come from the",
        "# zone's own entry; substitutions let bench.yaml point a zone at the",
        "# onboard pixel without editing this file.",
        "light:",
    ]
    for zi, z in enumerate(zones):
        zid = z["id"]
        lay = layouts[zid]
        if lay.n == 0:
            out.append(f"  # {zid}: nothing wired — no strip emitted.")
            continue
        pin = z.get("pin", 18)
        rgbw = str(bool(z.get("rgbw", True))).lower()
        out += [
            "  - platform: esp32_rmt_led_strip",
            f"    id: zone_{zid}",
            f'    name: "Castle {zid}"',
            f"    pin: GPIO${{pin_{zid}}}",
            f"    num_leds: ${{px_{zid}}}",
            "    chipset: WS2812",
            f"    rgb_order: {z.get('rgb_order', 'GRB')}",
            f"    is_rgbw: ${{rgbw_{zid}}}",
            # Explicit, and budgeted: see RMT_TOTAL_SYMBOLS above for why
            # ESPHome's S2 default of 192 leaves two strips dark, and why a
            # long strip may be worth a second block.
            f"    rmt_symbols: {rmt_symbols(z)}",
            # Internal RAM, deliberately: the strip buffer is under 50 bytes,
            # and the RMT refill ISR must be able to read it during flash-cache
            # blackouts. PSRAM there truncated frames at 4 px on every strip
            # after the first (bench-diagnosed 2026-08-19).
            "    use_psram: false",
            "    default_transition_length: 0s",
            "    effects:",
            EFFECT,
            '          name: "Show"',
            "          update_interval: 16ms",
            "          lambda: |-",
            "            using namespace castle;",
            f"            const Fixture &fx = RIG[{zi}];",
            "            static uint8_t buf[RIG_MAX_PIXELS * 4];",
            "            ZoneIo io{",
            f"                &id(zone_flash)[{zi}], &id(zone_flash_target)[{zi}],",
            f"                &id(zone_flash_rise)[{zi}], id(zone_flash_decay)[{zi}],",
            f"                &id(zone_flash_col)[{zi * 4}],",
            f"                id(zone_level)[{zi}], id(zone_phase)[{zi}],",
            f"                (float) id(trim_{zid.lower()}).state,",
            "                (float) id(hue_balance).state,",
            f"                id(zone_effect)[{zi}], id(zone_center)[{zi}],",
            f"                id(zone_overlay)[{zi}], id(zone_palette)[{zi}],",
            f"                id(zone_flash_mode)[{zi}], id(zone_flash_epoch)[{zi}],",
            "                id(soften).state};",
            "            step_flash(io);",
            "            render_zone(buf, %d, fx, millis() / 1000.0f, io);" % zi,
            "            for (int p = 0; p < fx.n; p++)",
            "              it[p] = Color(buf[p * 4], buf[p * 4 + 1],",
            "                            buf[p * 4 + 2], buf[p * 4 + 3]);",
            *TEST_EFFECTS,
        ]
        out.append(f"    # {zid}: {z.get('fixture', f'{per} uniform')} "
                   f"— {lay.n} px, rgbw {rgbw}, GPIO{pin}")

    # One override for all the strips at once. The web remote and the boot
    # sequence want to talk to "the pixels", and with a strip per zone that is
    # no longer a single `id()`. Generated rather than hand-written in
    # castle_sd.yaml so the zone list stays in exactly one place.
    spare = check_rmt_budget(zones, layouts)
    out.append(f"# RMT: {RMT_TOTAL_SYMBOLS - spare} of {RMT_TOTAL_SYMBOLS} "
               f"symbols spent, {spare // RMT_BLOCK} block(s) spare "
               f"(the SD build's status pixel needs one).")
    live = [z["id"] for z in zones if layouts[z["id"]].n > 0]
    zone_rgbw = {z["id"]: bool(z.get("rgbw", True)) for z in zones}
    out += [
        "",
        "script:",
        "  - id: lights_override",
        "    mode: restart",
        "    parameters:",
        "      arg: string",
        "    then:",
        "      - lambda: |-",
        "          esphome::light::LightState *zones[] = {"
        + ", ".join(f"id(zone_{z})" for z in live) + "};",
        '          const char *names[] = {' + ", ".join(f'"{z}"' for z in live) + "};",
        "          const bool rgbw[] = {"
        + ", ".join(str(bool(zone_rgbw[z])).lower() for z in live) + "};",
        '          // "[zone:]spec[@pct]": spec = RRGGBB | white | off | show; one',
        "          // strip when a zone is named (the desk's channel test), pct 1..100.",
        "          std::string spec = arg, only;",
        "          const auto colon = arg.find(':');",
        "          if (colon != std::string::npos) {",
        "            only = arg.substr(0, colon); spec = arg.substr(colon + 1);",
        "          }",
        "          float bright = 1.0f;",
        "          const auto at = spec.find('@');",
        "          if (at != std::string::npos) {",
        "            bright = atoi(spec.c_str() + at + 1) / 100.0f; spec.resize(at);",
        "          }",
        f"          for (size_t i = 0; i < {len(live)}; i++) {{",
        "            if (!only.empty() && only != names[i]) continue;",
        "            auto *z = zones[i];",
        '            if (spec == "off") { z->turn_off().perform(); continue; }',
        "            auto call = z->turn_on();",
        "            call.set_brightness(bright);",
        '            if (spec == "show") {',
        '              call.set_effect("Show");',
        '            } else if (spec == "bars" || spec == "chase" || spec == "ends") {',
        "              // The bench patterns, one effect each (TEST_EFFECTS).",
        '              call.set_effect(spec == "bars" ? "Test Bars"',
        '                              : spec == "chase" ? "Test Chase" : "Test Ends");',
        '            } else if (spec == "white") {',
        "              // The white LED itself on an RGBW fixture; an RGB one",
        "              // mixes it. Tests the one channel a colour never lights.",
        '              call.set_effect("None");',
        "              if (rgbw[i]) call.set_rgbw(0.0f, 0.0f, 0.0f, 1.0f);",
        "              else call.set_rgb(1.0f, 1.0f, 1.0f);",
        "            } else {",
        "              // Park on a colour, no animation. White channel OFF:",
        "              // left alone it kept whatever the effect last wrote,",
        "              // and 'red' came out pink on the jewels (2026-08-21).",
        "              long v = strtol(spec.c_str(), nullptr, 16);",
        '              call.set_effect("None");',
        "              call.set_rgbw(((v >> 16) & 0xFF) / 255.0f,",
        "                            ((v >> 8) & 0xFF) / 255.0f,",
        "                            (v & 0xFF) / 255.0f, 0.0f);",
        "            }",
        "            call.perform();",
        "          }",
    ]
    return "\n".join(out) + "\n"


