#!/usr/bin/env python3
"""Regenerate requirements-desktop.lock — the desktop tools' hash-pinned lock.

requirements.lock (tools/lock_deps.py) is the HARDWARE side: esphome and
what tools/ imports, installed by CI on Linux. The desktop tools are a
different install on different machines — a buyer's Windows PC or an Apple
Silicon Mac, set up by installer/install.ps1 / install.sh — and they carry
torch through demucs, so they get their own lock rather than a section of
that one.

It is a UNIVERSAL lock: one file, every pin wearing the environment marker
it applies under, every distribution file's sha256 under it, so the same
`uv pip install --require-hashes` works on both platforms. `uv pip compile
--universal` cannot write it — demucs 4.1.0 asks for numpy<2 on Intel macOS
(torch stopped shipping x86_64 macOS wheels), which contradicts our
numpy~=2.5 and fails the whole resolve. So the resolve is a throwaway uv
PROJECT whose `environments` names exactly the platforms the installer
supports, and `uv export` turns its uv.lock into requirements form. Linux
is deliberately absent: PyPI's Linux torch is the CUDA build and pulls
~3 GB of nvidia wheels for a decoration's song importer.

yt-dlp is in requirements-desktop.txt (the Mac-only install_castle_tools.sh
still pip-installs it) and deliberately NOT in this lock: the installer
fetches the standalone yt-dlp binary instead, so it can be updated on its
own when a site breaks old clients, without re-locking torch.

Run it as `make lock-desktop`. It needs uv on PATH and the network.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "requirements-desktop.txt"
LOCK = ROOT / "requirements-desktop.lock"

#: The platforms the lock resolves for, as uv `environments` markers. Each
#: is a platform the installer has a castle-core build for (the release's
#: `castle-core-<rust-target>-<tag>.zip`), minus Intel macOS — see above.
ENVIRONMENTS = (
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
)
#: Named in requirements-desktop.txt, fetched as a standalone binary instead.
NOT_LOCKED = ("yt-dlp",)

HEADER = """\
# requirements-desktop.lock — GENERATED by tools/lock_desktop.py (make lock-desktop).
# The desktop tools' universal lock: macOS arm64 + Windows x64, hash-pinned.
# installer/install.sh and install.ps1 install it with --require-hashes.
"""

_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def norm(name: str) -> str:
    """PEP 503 normalisation."""
    return re.sub(r"[-_.]+", "-", name).lower()


def requirements(text: str) -> list[str]:
    """requirements-desktop.txt's requirement lines, minus NOT_LOCKED."""
    skip = {norm(n) for n in NOT_LOCKED}
    out = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        m = _NAME.match(line)
        if m and norm(m.group(1)) not in skip:
            out.append(line)
    return out


def project_toml(reqs: list[str]) -> str:
    """The throwaway project the resolve runs in."""
    # A JSON string is a valid TOML basic string, quotes and all.
    deps = ",\n".join(f"  {json.dumps(r)}" for r in reqs)
    envs = ",\n".join(f"  {json.dumps(e)}" for e in ENVIRONMENTS)
    return (
        "[project]\n"
        'name = "castle-desktop-lock"\n'
        'version = "0"\n'
        'requires-python = ">=3.13,<3.14"\n'
        f"dependencies = [\n{deps},\n]\n\n"
        "[tool.uv]\n"
        "package = false\n"
        f"environments = [\n{envs},\n]\n"
    )


def resolve(reqs: list[str], uv: str) -> str:
    """uv lock + uv export in a temp project; the requirements-form text."""
    with tempfile.TemporaryDirectory(prefix="castle-desktop-lock-") as tmp:
        (Path(tmp) / "pyproject.toml").write_text(project_toml(reqs), encoding="utf-8")
        subprocess.run([uv, "lock", "--quiet"], cwd=tmp, check=True)
        out = subprocess.run(
            [
                uv,
                "export",
                "--format",
                "requirements-txt",
                "--no-emit-project",
                "--no-header",
                "--quiet",
            ],
            cwd=tmp,
            check=True,
            capture_output=True,
            text=True,
        )
    return out.stdout


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=LOCK)
    args = ap.parse_args(argv)
    uv = shutil.which("uv")
    if not uv:
        print(
            "lock-desktop: uv is not on PATH (https://docs.astral.sh/uv/)",
            file=sys.stderr,
        )
        return 1
    reqs = requirements(SOURCE.read_text(encoding="utf-8"))
    body = resolve(reqs, uv)
    args.out.write_text(HEADER + body, encoding="utf-8")
    pins = sum(1 for ln in body.splitlines() if _NAME.match(ln) and "==" in ln)
    print(f"{args.out.name}: {pins} pins for {len(ENVIRONMENTS)} platforms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
